import glob
import json
import os
import sys
import tempfile
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from pydantic import BaseModel
import pytest

from fhircraft.config import with_config
from fhircraft.fhir.resources.factory import (
    ConstructionMode,
    ResourceFactory,
    construct_resource_model,
    factory,
)
from fhircraft.fhir.resources.generator import CodeGenerator

VERSIONS = ["R4B", "R5"]
CORE_EXAMPLES_DIRECTORY = f"test/static/fhir-core-examples"
CORE_DEFINITIONS_DIRECTORY = f"test/static/fhir-core-definitions"
PROFILES_EXAMPLES_DIRECTORY = f"test/static/fhir-profiles-examples"
PROFILES_DEFINTIONS_DIRECTORY = f"test/static/fhir-profiles-definitions"


def _get_core_example_filenames(prefix, version):
    pattern = os.path.join(f"{CORE_EXAMPLES_DIRECTORY}/{version}", prefix)
    example_files = [os.path.basename(f) for f in glob.glob(pattern)]
    return example_files


fhir_resources_test_cases = {
    version: [
        case
        for cases in [
            [
                (resource_label, filename)
                for filename in _get_core_example_filenames(
                    f"{resource_label.lower()}-*.json", version
                )
            ]
            for resource_label in [
                "Observation",
                "Condition",
                "Patient",
                "Practitioner",
                "Procedure",
                "MedicationAdministration",
                "Organization",
                "StructureMap",
                "ConceptMap",
                "DiagnosticReport",
                "",
            ]
        ]
        for case in cases
    ]
    for version in VERSIONS
}


def _assert_construct_core_resource(version, resource_label, filename):

    with with_config(validation_mode="skip"):
        # Disable internet access to ensure we use local definitions
        factory.disable_internet_access()
        # Load the FHIR resource definition from local files
        factory.load_definitions_from_files(
            Path(CORE_DEFINITIONS_DIRECTORY)
            / Path(version)
            / Path(f"{resource_label.lower()}.profile.json")
        )

    fhir_version = {
        "R4B": "4.3.0",
        "R5": "5.0.0",
    }.get(version, version)

    # Generate source code for Pydantic FHIR model
    resource = factory.construct_resource_model(
        canonical_url=f"http://hl7.org/fhir/StructureDefinition/{resource_label}|{fhir_version}",
        mode=ConstructionMode.SNAPSHOT,
    )
    # Load example FHIR resource data
    with open(
        os.path.join(os.path.abspath(f"{CORE_EXAMPLES_DIRECTORY}/{version}"), filename),
        encoding="utf8",
    ) as file:
        fhir_resource_data = json.load(file)

    # Use the factory-constructed model to validate the FHIR resource data
    assert (
        instance := resource.model_validate(fhir_resource_data)
    ), "Factory model failed to validate the example resource data"
    assert fhir_resource_data == json.loads(
        instance.model_dump_json()
    ), "Factory model failed to recreate the original resource data"

    # Create temp directory for storing generated code
    with tempfile.TemporaryDirectory() as d:

        source_code = CodeGenerator().generate_resource_model_code(resource)
        # Store source code in a file
        temp_file_name = os.path.join(d, "temp_test.py")
        with open(temp_file_name, "w") as test_file:
            test_file.write(source_code)
        # Load the Pydantic FHIR model
        spec = spec_from_file_location("module", temp_file_name)
        if not spec or not spec.loader:
            raise ImportError(f"Could not load module from {temp_file_name}")
        module = module_from_spec(spec)
        if not module:
            raise ImportError(f"Could not create module from spec {spec}")
        sys.modules["module.name"] = module
        spec.loader.exec_module(module)
        # Use the auto-generated model to validate a FHIR resource
        coded_model: BaseModel = getattr(module, resource_label)

        # Use the code-loaded model to validate the FHIR resource data
        assert (
            instance := coded_model.model_validate(fhir_resource_data)
        ), "Autogenerated code model failed to validate the example resource data"
        assert fhir_resource_data == json.loads(
            instance.model_dump_json()
        ), "Autogenerated code model failed to recreate the original resource data"


@pytest.mark.integration
@pytest.mark.parametrize("resource_label, filename", fhir_resources_test_cases["R4B"])
def test_construct_R4B_core_resource(resource_label, filename):
    _assert_construct_core_resource("R4B", resource_label, filename)


@pytest.mark.integration
@pytest.mark.parametrize("resource_label, filename", fhir_resources_test_cases["R5"])
def test_construct_R5_core_resource(resource_label, filename):
    _assert_construct_core_resource("R5", resource_label, filename)


def _get_profiles_example_filenames(prefix):
    pattern = os.path.join(f"{PROFILES_EXAMPLES_DIRECTORY}", prefix)
    example_files = [os.path.basename(f) for f in glob.glob(pattern)]
    return example_files


fhir_profiles_test_cases = [
    case
    for cases in [
        [
            filename
            for filename in _get_profiles_example_filenames(f"{resource_label}-*")
        ]
        for resource_label in [
            "Observation",
            "Condition",
            "Patient",
        ]
    ]
    for case in cases
]


@pytest.mark.integration
@pytest.mark.parametrize(
    "mode", [ConstructionMode.DIFFERENTIAL, ConstructionMode.SNAPSHOT]
)
@pytest.mark.parametrize("filename", fhir_profiles_test_cases)
@pytest.mark.filterwarnings("ignore:.*eld-24.*")
def test_construct_profiled_resource(mode, filename):
    # Use the auto-generated model to validate a FHIR resource
    with open(
        os.path.join(os.path.abspath(f"{PROFILES_EXAMPLES_DIRECTORY}"), filename),
        encoding="utf8",
    ) as file:
        fhir_resource = json.load(file)

    # Create temp directory for storing generated code
    with tempfile.TemporaryDirectory() as d:
        with with_config(validation_mode="skip"):
            # Disable internet access to ensure we use local definitions
            factory.disable_internet_access()
            # Load the FHIR resource definition from local files
            factory.load_definitions_from_directory(Path(PROFILES_DEFINTIONS_DIRECTORY))
            factory.clear_cache()
        # Generate source code for Pydantic FHIR model
        resource = construct_resource_model(
            canonical_url=fhir_resource["meta"]["profile"][0],
            mode=mode,
        )
        assert (
            json.loads(resource.model_validate(fhir_resource).model_dump_json())
            == fhir_resource
        )
        source_code = CodeGenerator().generate_resource_model_code(resource)
        # Store source code in a file
        temp_file_name = os.path.join(d, f"temp_test_{resource.__name__}.py")
        with open(temp_file_name, "w") as test_file:
            test_file.write(source_code)
        # Load the Pydantic FHIR model
        spec = spec_from_file_location("module", temp_file_name)
        if not spec or not spec.loader:
            raise ImportError(f"Could not load module from {temp_file_name}")
        module = module_from_spec(spec)
        if not module:
            raise ImportError(f"Could not create module from spec {spec}")
        sys.modules["module.name"] = module
        spec.loader.exec_module(module)

    fhir_resource_instance = getattr(module, resource.__name__).model_validate(
        fhir_resource
    )
    assert json.loads(fhir_resource_instance.model_dump_json()) == fhir_resource


def _normalize(s):
    import re

    return re.sub(r"\s+", " ", s.strip())


def assertBlockInCode(code, expected_block):
    # Generate source code
    # Assert code block (normalized)
    norm_expected = _normalize(expected_block)
    norm_code = _normalize(code)
    assert (
        norm_expected in norm_code
    ), f"Expected block not found in generated code.\n\nExpected:\n{expected_block}\n\nGot:\n{code}"


def test_regression_issue_255():

    factory = ResourceFactory()

    structure_definition = {
        "resourceType": "StructureDefinition",
        "id": "example",
        "url": "http://example.org/fhir/StructureDefinition/example",
        "version": "5.0.0",
        "name": "ProfileExample",
        "title": "Example Profile",
        "status": "draft",
        "fhirVersion": "5.0.0",
        "kind": "resource",
        "abstract": False,
        "type": "Observation",
        "derivation": "constraint",
        "baseDefinition": "http://hl7.org/fhir/StructureDefinition/Observation",
        "differential": {
            "element": [
                {
                    "id": "Observation",
                    "path": "Observation",
                    "min": 0,
                    "max": "*",
                },
                {
                    "id": "Observation.code",
                    "path": "Observation.code",
                },
                {
                    "id": "Observation.code.coding",
                    "path": "Observation.code.coding",
                    "slicing": {
                        "discriminator": [
                            {"type": "value", "path": "code"},
                            {"type": "value", "path": "system"},
                        ],
                        "ordered": False,
                        "rules": "open",
                    },
                },
                {
                    "id": "Observation.code.coding:slicedCoding",
                    "path": "Observation.code.coding",
                    "sliceName": "slicedCoding",
                    "min": 1,
                    "max": "1",
                },
                {
                    "id": "Observation.code.coding:slicedCoding.system",
                    "path": "Observation.code.coding.system",
                    "min": 1,
                    "max": "1",
                    "type": [{"code": "uri"}],
                    "fixedUri": "http://example.org",
                },
                {
                    "id": "Observation.code.coding:slicedCoding.code",
                    "path": "Observation.code.coding.code",
                    "min": 1,
                    "max": "1",
                    "type": [{"code": "code"}],
                    "fixedCode": "12345-6",
                },
            ]
        },
    }

    model = factory.construct_resource_model(
        structure_definition=structure_definition, mode="differential"
    )

    source_code = CodeGenerator().generate_resource_model_code(model)

    expected_code = '''
    class ProfileExampleSlicedCoding(Coding, FHIRSliceModel):
        min_cardinality: ClassVar[int] = 1
        max_cardinality: ClassVar[int] = 1
    
    
        system: Literal['http://example.org'] = Field(
            description=None,
            default="http://example.org",
        )
        code: Literal['12345-6'] = Field(
            description=None,
            default="12345-6",
        )
        
        
    class ProfileExampleCode(CodeableConcept):
        """
        Describes what was observed. Sometimes this is called the observation "name".
        """
    

        coding: Optional[List[Annotated[Union[ProfileExampleSlicedCoding, Coding], Field(union_mode='left_to_right')]]] = Field(
            description=None,
            default=None,
        )
        
        @field_validator(*('coding',), mode="after", check_fields=None)
        @classmethod
        def coding_slicing_cardinality_validator(cls, value):    
            return validate_slicing_cardinalities(cls, value, 
                field_name="coding",
            )
        
    class ProfileExample(Observation):

        _canonical_url = "http://example.org/fhir/StructureDefinition/example"

        meta: Optional[Meta] = Field(
            title="Meta",
            description="Metadata about the resource.",
            default_factory=lambda: Meta(profile=['http://example.org/fhir/StructureDefinition/example']),
        )
        code: Optional[ProfileExampleCode] = Field(
            description="Type of observation (code / type)",
            default=None,
        )
    '''

    assertBlockInCode(source_code, expected_code.strip())


def test_regression_issue_258():

    factory = ResourceFactory()

    structure_definition = {
        "resourceType": "StructureDefinition",
        "id": "example",
        "url": "http://example.org/fhir/StructureDefinition/example",
        "version": "5.0.0",
        "name": "ProfileExample",
        "title": "Example Profile",
        "status": "draft",
        "fhirVersion": "5.0.0",
        "kind": "resource",
        "abstract": False,
        "type": "Observation",
        "derivation": "constraint",
        "baseDefinition": "http://hl7.org/fhir/StructureDefinition/Observation",
        "differential": {
            "element": [
                {"id": "Observation", "path": "Observation", "min": 0, "max": "*"},
                {
                    "id": "Observation.category",
                    "path": "Observation.category",
                    "slicing": {"discriminator": [{"type": "value", "path": "coding"}]},
                },
                {
                    "id": "Observation.category:slice",
                    "path": "Observation.category",
                    "max": "2",
                    "sliceName": "slice",
                    "patternCodeableConcept": {
                        "coding": [
                            {
                                "system": "http://example.org",
                                "code": "12345-6",
                                "display": "Fixed Category",
                            }
                        ]
                    },
                },
            ]
        },
    }

    model = factory.construct_resource_model(
        structure_definition=structure_definition, mode="differential"
    )

    source_code = CodeGenerator().generate_resource_model_code(model)

    expected_code = '''
    class ProfileExampleSlice(CodeableConcept, FHIRSliceModel):
        """
        Classification of  type of observation
        """
        min_cardinality: ClassVar[int] = 0
        max_cardinality: ClassVar[int] = 2

        coding: Optional[List[Coding]] = Field(
            description="Code defined by a terminology system",
            default=[Coding(code="12345-6", display="Fixed Category", system="http://example.org")],
        )
        
        @model_validator(mode="after")
        def FHIR_slice_pattern_constraint(self):    
            return validate_FHIR_element_pattern(
                self,
                cls=None,
                pattern=CodeableConcept(coding=[Coding(code="12345-6", display="Fixed Category", system="http://example.org")]),
            )
    
    class ProfileExample(Observation):

        _canonical_url = "http://example.org/fhir/StructureDefinition/example"

        meta: Optional[Meta] = Field(
            title="Meta",
            description="Metadata about the resource.",
            default_factory=lambda: Meta(profile=['http://example.org/fhir/StructureDefinition/example']),
        )
        category: Optional[List[Annotated[Union[ProfileExampleSlice, CodeableConcept], Field(union_mode='left_to_right')]]] = Field(
            description="Classification of  type of observation",
            default=None,
        )
        
        @field_validator(*('category',), mode="after", check_fields=None)
        @classmethod
        def category_slicing_cardinality_validator(cls, value):    
            return validate_slicing_cardinalities(cls, value, 
                field_name="category",
            )
    '''

    assertBlockInCode(source_code, expected_code.strip())
