from .group import GroupCharacteristic, GroupMember, Group
from .activity_definition import ActivityDefinitionParticipant, ActivityDefinitionDynamicValue, ActivityDefinition
from .flag import Flag
from .event_definition import EventDefinition
from .artifact_assessment import ArtifactAssessmentContent, ArtifactAssessment
from .healthcare_service import HealthcareServiceEligibility, HealthcareService
from .subscription import SubscriptionFilterBy, SubscriptionParameter, Subscription
from .search_parameter import SearchParameterComponent, SearchParameter
from .clinical_use_definition import ClinicalUseDefinitionContraindicationOtherTherapy, ClinicalUseDefinitionContraindication, ClinicalUseDefinitionIndication, ClinicalUseDefinitionInteractionInteractant, ClinicalUseDefinitionInteraction, ClinicalUseDefinitionUndesirableEffect, ClinicalUseDefinitionWarning, ClinicalUseDefinition
from .body_structure import BodyStructureIncludedStructureBodyLandmarkOrientationDistanceFromLandmark, BodyStructureIncludedStructureBodyLandmarkOrientation, BodyStructureIncludedStructure, BodyStructure
from .graph_definition import GraphDefinitionNode, GraphDefinitionLinkCompartment, GraphDefinitionLink, GraphDefinition
from .terminology_capabilities import TerminologyCapabilitiesSoftware, TerminologyCapabilitiesImplementation, TerminologyCapabilitiesCodeSystemVersionFilter, TerminologyCapabilitiesCodeSystemVersion, TerminologyCapabilitiesCodeSystem, TerminologyCapabilitiesExpansionParameter, TerminologyCapabilitiesExpansion, TerminologyCapabilitiesValidateCode, TerminologyCapabilitiesTranslation, TerminologyCapabilitiesClosure, TerminologyCapabilities
from .practitioner_role import PractitionerRole
from .capability_statement import CapabilityStatementSoftware, CapabilityStatementImplementation, CapabilityStatementRestSecurity, CapabilityStatementRestResourceInteraction, CapabilityStatementRestResourceSearchParam, CapabilityStatementRestResourceOperation, CapabilityStatementRestResource, CapabilityStatementRestInteraction, CapabilityStatementRest, CapabilityStatementMessagingEndpoint, CapabilityStatementMessagingSupportedMessage, CapabilityStatementMessaging, CapabilityStatementDocument, CapabilityStatement
from .substance_polymer import SubstancePolymerMonomerSetStartingMaterial, SubstancePolymerMonomerSet, SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation, SubstancePolymerRepeatRepeatUnitStructuralRepresentation, SubstancePolymerRepeatRepeatUnit, SubstancePolymerRepeat, SubstancePolymer
from .concept_map import ConceptMapProperty, ConceptMapAdditionalAttribute, ConceptMapGroupElementTargetProperty, ConceptMapGroupElementTargetDependsOn, ConceptMapGroupElementTarget, ConceptMapGroupElement, ConceptMapGroupUnmapped, ConceptMapGroup, ConceptMap
from .list import ListEntry, List
from .nutrition_intake import NutritionIntakeConsumedItem, NutritionIntakeIngredientLabel, NutritionIntakePerformer, NutritionIntake
from .communication import CommunicationPayload, Communication
from .metadata_resource import MetadataResource
from .value_set import ValueSetComposeIncludeConceptDesignation, ValueSetComposeIncludeConcept, ValueSetComposeIncludeFilter, ValueSetComposeInclude, ValueSetCompose, ValueSetExpansionParameter, ValueSetExpansionProperty, ValueSetExpansionContainsPropertySubProperty, ValueSetExpansionContainsProperty, ValueSetExpansionContains, ValueSetExpansion, ValueSetScope, ValueSet
from .provenance import ProvenanceAgent, ProvenanceEntity, Provenance
from .claim_response import ClaimResponseEvent, ClaimResponseItemReviewOutcome, ClaimResponseItemAdjudication, ClaimResponseItemDetailSubDetail, ClaimResponseItemDetail, ClaimResponseItem, ClaimResponseAddItemBodySite, ClaimResponseAddItemDetailSubDetail, ClaimResponseAddItemDetail, ClaimResponseAddItem, ClaimResponseTotal, ClaimResponsePayment, ClaimResponseProcessNote, ClaimResponseInsurance, ClaimResponseError, ClaimResponse
from .observation_definition import ObservationDefinitionQualifiedValue, ObservationDefinitionComponent, ObservationDefinition
from .family_member_history import FamilyMemberHistoryParticipant, FamilyMemberHistoryCondition, FamilyMemberHistoryProcedure, FamilyMemberHistory
from .evidence_report import EvidenceReportSubjectCharacteristic, EvidenceReportSubject, EvidenceReportRelatesToTarget, EvidenceReportRelatesTo, EvidenceReportSection, EvidenceReport
from .medication_request import MedicationRequestDispenseRequestInitialFill, MedicationRequestDispenseRequest, MedicationRequestSubstitution, MedicationRequest
from .manufactured_item_definition import ManufacturedItemDefinitionProperty, ManufacturedItemDefinitionComponentConstituent, ManufacturedItemDefinitionComponent, ManufacturedItemDefinition
from .test_script import TestScriptOrigin, TestScriptDestination, TestScriptMetadataLink, TestScriptMetadataCapability, TestScriptMetadata, TestScriptScope, TestScriptFixture, TestScriptVariable, TestScriptSetupActionOperationRequestHeader, TestScriptSetupActionOperation, TestScriptSetupActionAssertRequirement, TestScriptSetupActionAssert, TestScriptSetupAction, TestScriptSetup, TestScriptTestAction, TestScriptTest, TestScriptTeardownAction, TestScriptTeardown, TestScript
from .administrable_product_definition import AdministrableProductDefinitionProperty, AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod, AdministrableProductDefinitionRouteOfAdministrationTargetSpecies, AdministrableProductDefinitionRouteOfAdministration, AdministrableProductDefinition
from .test_plan import TestPlanDependency, TestPlanTestCaseDependency, TestPlanTestCaseTestRunScript, TestPlanTestCaseTestRun, TestPlanTestCaseTestData, TestPlanTestCaseAssertion, TestPlanTestCase, TestPlan
from .enrollment_response import EnrollmentResponse
from .condition import ConditionParticipant, ConditionStage, Condition
from .specimen import SpecimenFeature, SpecimenCollection, SpecimenProcessing, SpecimenContainer, Specimen
from .message_definition import MessageDefinitionFocus, MessageDefinitionAllowedResponse, MessageDefinition
from .citation import CitationSummary, CitationClassification, CitationStatusDate, CitationCitedArtifactVersion, CitationCitedArtifactStatusDate, CitationCitedArtifactTitle, CitationCitedArtifactAbstract, CitationCitedArtifactPart, CitationCitedArtifactRelatesTo, CitationCitedArtifactPublicationFormPublishedIn, CitationCitedArtifactPublicationForm, CitationCitedArtifactWebLocation, CitationCitedArtifactClassification, CitationCitedArtifactContributorshipEntryContributionInstance, CitationCitedArtifactContributorshipEntry, CitationCitedArtifactContributorshipSummary, CitationCitedArtifactContributorship, CitationCitedArtifact, Citation
from .regulated_authorization import RegulatedAuthorizationCase, RegulatedAuthorization
from .permission import PermissionJustification, PermissionRuleDataResource, PermissionRuleData, PermissionRuleActivity, PermissionRule, Permission
from .structure_definition import StructureDefinitionMapping, StructureDefinitionContext, StructureDefinitionSnapshot, StructureDefinitionDifferential, StructureDefinition
from .verification_result import VerificationResultPrimarySource, VerificationResultAttestation, VerificationResultValidator, VerificationResult
from .device_dispense import DeviceDispensePerformer, DeviceDispense
from .evidence import EvidenceVariableDefinition, EvidenceStatisticSampleSize, EvidenceStatisticAttributeEstimate, EvidenceStatisticModelCharacteristicVariable, EvidenceStatisticModelCharacteristic, EvidenceStatistic, EvidenceCertainty, Evidence
from .device_definition import DeviceDefinitionUdiDeviceIdentifierMarketDistribution, DeviceDefinitionUdiDeviceIdentifier, DeviceDefinitionRegulatoryIdentifier, DeviceDefinitionDeviceName, DeviceDefinitionClassification, DeviceDefinitionConformsTo, DeviceDefinitionHasPart, DeviceDefinitionPackagingDistributor, DeviceDefinitionPackaging, DeviceDefinitionVersion, DeviceDefinitionProperty, DeviceDefinitionLink, DeviceDefinitionMaterial, DeviceDefinitionGuideline, DeviceDefinitionCorrectiveAction, DeviceDefinitionChargeItem, DeviceDefinition
from .requirements import RequirementsStatement, Requirements
from .device import DeviceUdiCarrier, DeviceName, DeviceVersion, DeviceConformsTo, DeviceProperty, Device
from .formulary_item import FormularyItem
from .condition_definition import ConditionDefinitionObservation, ConditionDefinitionMedication, ConditionDefinitionPrecondition, ConditionDefinitionQuestionnaire, ConditionDefinitionPlan, ConditionDefinition
from .specimen_definition import SpecimenDefinitionTypeTestedContainerAdditive, SpecimenDefinitionTypeTestedContainer, SpecimenDefinitionTypeTestedHandling, SpecimenDefinitionTypeTested, SpecimenDefinition
from .adverse_event import AdverseEventParticipant, AdverseEventSuspectEntityCausality, AdverseEventSuspectEntity, AdverseEventContributingFactor, AdverseEventPreventiveAction, AdverseEventMitigatingAction, AdverseEventSupportingInfo, AdverseEvent
from .appointment_response import AppointmentResponse
from .nutrition_product import NutritionProductNutrient, NutritionProductIngredient, NutritionProductCharacteristic, NutritionProductInstance, NutritionProduct
from .practitioner import PractitionerQualification, PractitionerCommunication, Practitioner
from .substance_definition import SubstanceDefinitionMoiety, SubstanceDefinitionCharacterization, SubstanceDefinitionProperty, SubstanceDefinitionMolecularWeight, SubstanceDefinitionStructureRepresentation, SubstanceDefinitionStructure, SubstanceDefinitionCode, SubstanceDefinitionNameOfficial, SubstanceDefinitionName, SubstanceDefinitionRelationship, SubstanceDefinitionSourceMaterial, SubstanceDefinition
from .clinical_impression import ClinicalImpressionFinding, ClinicalImpression
from .patient import PatientContact, PatientCommunication, PatientLink, Patient
from .inventory_item import InventoryItemName, InventoryItemResponsibleOrganization, InventoryItemDescription, InventoryItemAssociation, InventoryItemCharacteristic, InventoryItemInstance, InventoryItem
from .immunization import ImmunizationPerformer, ImmunizationProgramEligibility, ImmunizationReaction, ImmunizationProtocolApplied, Immunization
from .subscription_topic import SubscriptionTopicResourceTriggerQueryCriteria, SubscriptionTopicResourceTrigger, SubscriptionTopicEventTrigger, SubscriptionTopicCanFilterBy, SubscriptionTopicNotificationShape, SubscriptionTopic
from .medication_knowledge import MedicationKnowledgeRelatedMedicationKnowledge, MedicationKnowledgeMonograph, MedicationKnowledgeCost, MedicationKnowledgeMonitoringProgram, MedicationKnowledgeIndicationGuidelineDosingGuidelineDosage, MedicationKnowledgeIndicationGuidelineDosingGuidelinePatientCharacteristic, MedicationKnowledgeIndicationGuidelineDosingGuideline, MedicationKnowledgeIndicationGuideline, MedicationKnowledgeMedicineClassification, MedicationKnowledgePackaging, MedicationKnowledgeStorageGuidelineEnvironmentalSetting, MedicationKnowledgeStorageGuideline, MedicationKnowledgeRegulatorySubstitution, MedicationKnowledgeRegulatoryMaxDispense, MedicationKnowledgeRegulatory, MedicationKnowledgeDefinitionalIngredient, MedicationKnowledgeDefinitionalDrugCharacteristic, MedicationKnowledgeDefinitional, MedicationKnowledge
from .transport import TransportRestriction, TransportInput, TransportOutput, Transport
from .episode_of_care import EpisodeOfCareStatusHistory, EpisodeOfCareReason, EpisodeOfCareDiagnosis, EpisodeOfCare
from .composition import CompositionAttester, CompositionEvent, CompositionSection, Composition
from .substance_nucleic_acid import SubstanceNucleicAcidSubunitLinkage, SubstanceNucleicAcidSubunitSugar, SubstanceNucleicAcidSubunit, SubstanceNucleicAcid
from .naming_system import NamingSystemUniqueId, NamingSystem
from .request_orchestration import RequestOrchestrationActionCondition, RequestOrchestrationActionInput, RequestOrchestrationActionOutput, RequestOrchestrationActionRelatedAction, RequestOrchestrationActionParticipant, RequestOrchestrationActionDynamicValue, RequestOrchestrationAction, RequestOrchestration
from .actor_definition import ActorDefinition
from .biologically_derived_product_dispense import BiologicallyDerivedProductDispensePerformer, BiologicallyDerivedProductDispense
from .contract import ContractContentDefinition, ContractTermSecurityLabel, ContractTermOfferParty, ContractTermOfferAnswer, ContractTermOffer, ContractTermAssetContext, ContractTermAssetValuedItem, ContractTermAsset, ContractTermActionSubject, ContractTermAction, ContractTerm, ContractSigner, ContractFriendly, ContractLegal, ContractRule, Contract
from .consent import ConsentPolicyBasis, ConsentVerification, ConsentProvisionActor, ConsentProvisionData, ConsentProvision, Consent
from .subscription_status import SubscriptionStatusNotificationEvent, SubscriptionStatus
from .substance_source_material import SubstanceSourceMaterialFractionDescription, SubstanceSourceMaterialOrganismAuthor, SubstanceSourceMaterialOrganismHybrid, SubstanceSourceMaterialOrganismOrganismGeneral, SubstanceSourceMaterialOrganism, SubstanceSourceMaterialPartDescription, SubstanceSourceMaterial
from .example_scenario import ExampleScenarioActor, ExampleScenarioInstanceVersion, ExampleScenarioInstanceContainedInstance, ExampleScenarioInstance, ExampleScenarioProcessStepOperation, ExampleScenarioProcessStepAlternative, ExampleScenarioProcessStep, ExampleScenarioProcess, ExampleScenario
from .evidence_variable import EvidenceVariableCharacteristicDefinitionByTypeAndValue, EvidenceVariableCharacteristicDefinitionByCombination, EvidenceVariableCharacteristicTimeFromEvent, EvidenceVariableCharacteristic, EvidenceVariableCategory, EvidenceVariable
from .test_report import TestReportParticipant, TestReportSetupActionOperation, TestReportSetupActionAssertRequirement, TestReportSetupActionAssert, TestReportSetupAction, TestReportSetup, TestReportTestAction, TestReportTest, TestReportTeardownAction, TestReportTeardown, TestReport
from .canonical_resource import CanonicalResource
from .device_usage import DeviceUsageAdherence, DeviceUsage
from .claim import ClaimRelated, ClaimPayee, ClaimEvent, ClaimCareTeam, ClaimSupportingInfo, ClaimDiagnosis, ClaimProcedure, ClaimInsurance, ClaimAccident, ClaimItemBodySite, ClaimItemDetailSubDetail, ClaimItemDetail, ClaimItem, Claim
from .questionnaire import QuestionnaireItemEnableWhen, QuestionnaireItemAnswerOption, QuestionnaireItemInitial, QuestionnaireItem, Questionnaire
from .vision_prescription import VisionPrescriptionLensSpecificationPrism, VisionPrescriptionLensSpecification, VisionPrescription
from .risk_assessment import RiskAssessmentPrediction, RiskAssessment
from .charge_item_definition import ChargeItemDefinitionApplicability, ChargeItemDefinitionPropertyGroup, ChargeItemDefinition
from .payment_reconciliation import PaymentReconciliationAllocation, PaymentReconciliationProcessNote, PaymentReconciliation
from .guidance_response import GuidanceResponse
from .task import TaskPerformer, TaskRestriction, TaskInput, TaskOutput, Task
from .ingredient import IngredientManufacturer, IngredientSubstanceStrengthReferenceStrength, IngredientSubstanceStrength, IngredientSubstance, Ingredient
from .coverage_eligibility_request import CoverageEligibilityRequestEvent, CoverageEligibilityRequestSupportingInfo, CoverageEligibilityRequestInsurance, CoverageEligibilityRequestItemDiagnosis, CoverageEligibilityRequestItem, CoverageEligibilityRequest
from .enrollment_request import EnrollmentRequest
from .structure_map import StructureMapStructure, StructureMapConst, StructureMapGroupInput, StructureMapGroupRuleSource, StructureMapGroupRuleTargetParameter, StructureMapGroupRuleTarget, StructureMapGroupRuleDependent, StructureMapGroupRule, StructureMapGroup, StructureMap
from .medicinal_product_definition import MedicinalProductDefinitionContact, MedicinalProductDefinitionNamePart, MedicinalProductDefinitionNameUsage, MedicinalProductDefinitionName, MedicinalProductDefinitionCrossReference, MedicinalProductDefinitionOperation, MedicinalProductDefinitionCharacteristic, MedicinalProductDefinition
from .immunization_evaluation import ImmunizationEvaluation
from .imaging_study import ImagingStudySeriesPerformer, ImagingStudySeriesInstance, ImagingStudySeries, ImagingStudy
from .message_header import MessageHeaderDestination, MessageHeaderSource, MessageHeaderResponse, MessageHeader
from .explanation_of_benefit import ExplanationOfBenefitRelated, ExplanationOfBenefitEvent, ExplanationOfBenefitPayee, ExplanationOfBenefitCareTeam, ExplanationOfBenefitSupportingInfo, ExplanationOfBenefitDiagnosis, ExplanationOfBenefitProcedure, ExplanationOfBenefitInsurance, ExplanationOfBenefitAccident, ExplanationOfBenefitItemBodySite, ExplanationOfBenefitItemReviewOutcome, ExplanationOfBenefitItemAdjudication, ExplanationOfBenefitItemDetailSubDetail, ExplanationOfBenefitItemDetail, ExplanationOfBenefitItem, ExplanationOfBenefitAddItemBodySite, ExplanationOfBenefitAddItemDetailSubDetail, ExplanationOfBenefitAddItemDetail, ExplanationOfBenefitAddItem, ExplanationOfBenefitTotal, ExplanationOfBenefitPayment, ExplanationOfBenefitProcessNote, ExplanationOfBenefitBenefitBalanceFinancial, ExplanationOfBenefitBenefitBalance, ExplanationOfBenefit
from .supply_request import SupplyRequestParameter, SupplyRequest
from .immunization_recommendation import ImmunizationRecommendationRecommendationDateCriterion, ImmunizationRecommendationRecommendation, ImmunizationRecommendation
from .substance_protein import SubstanceProteinSubunit, SubstanceProtein
from .coverage_eligibility_response import CoverageEligibilityResponseEvent, CoverageEligibilityResponseInsuranceItemBenefit, CoverageEligibilityResponseInsuranceItem, CoverageEligibilityResponseInsurance, CoverageEligibilityResponseError, CoverageEligibilityResponse
from .related_person import RelatedPersonCommunication, RelatedPerson
from .imaging_selection import ImagingSelectionPerformer, ImagingSelectionInstanceImageRegion2D, ImagingSelectionInstanceImageRegion3D, ImagingSelectionInstance, ImagingSelection
from .communication_request import CommunicationRequestPayload, CommunicationRequest
from .molecular_sequence import MolecularSequenceRelativeStartingSequence, MolecularSequenceRelativeEdit, MolecularSequenceRelative, MolecularSequence
from .insurance_plan import InsurancePlanCoverageBenefitLimit, InsurancePlanCoverageBenefit, InsurancePlanCoverage, InsurancePlanPlanGeneralCost, InsurancePlanPlanSpecificCostBenefitCost, InsurancePlanPlanSpecificCostBenefit, InsurancePlanPlanSpecificCost, InsurancePlanPlan, InsurancePlan
from .medication import MedicationIngredient, MedicationBatch, Medication
from .care_team import CareTeamParticipant, CareTeam
from .operation_definition import OperationDefinitionParameterBinding, OperationDefinitionParameterReferencedFrom, OperationDefinitionParameter, OperationDefinitionOverload, OperationDefinition
from .person import PersonCommunication, PersonLink, Person
from .substance_reference_information import SubstanceReferenceInformationGene, SubstanceReferenceInformationGeneElement, SubstanceReferenceInformationTarget, SubstanceReferenceInformation
from .diagnostic_report import DiagnosticReportSupportingInfo, DiagnosticReportMedia, DiagnosticReport
from .encounter_history import EncounterHistoryLocation, EncounterHistory
from .compartment_definition import CompartmentDefinitionResource, CompartmentDefinition
from .service_request import ServiceRequestOrderDetailParameter, ServiceRequestOrderDetail, ServiceRequestPatientInstruction, ServiceRequest
from .medication_administration import MedicationAdministrationPerformer, MedicationAdministrationDosage, MedicationAdministration
from .code_system import CodeSystemFilter, CodeSystemProperty, CodeSystemConceptDesignation, CodeSystemConceptProperty, CodeSystemConcept, CodeSystem
from .detected_issue import DetectedIssueEvidence, DetectedIssueMitigation, DetectedIssue
from .questionnaire_response import QuestionnaireResponseItemAnswer, QuestionnaireResponseItem, QuestionnaireResponse
from .endpoint import EndpointPayload, Endpoint
from .measure import MeasureTerm, MeasureGroupPopulation, MeasureGroupStratifierComponent, MeasureGroupStratifier, MeasureGroup, MeasureSupplementalData, Measure
from .resource import Resource
from .supply_delivery import SupplyDeliverySuppliedItem, SupplyDelivery
from .research_subject import ResearchSubjectProgress, ResearchSubject
from .organization_affiliation import OrganizationAffiliation
from .medication_statement import MedicationStatementAdherence, MedicationStatement
from .document_reference import DocumentReferenceAttester, DocumentReferenceRelatesTo, DocumentReferenceContentProfile, DocumentReferenceContent, DocumentReference
from .schedule import Schedule
from .account import AccountCoverage, AccountGuarantor, AccountDiagnosis, AccountProcedure, AccountRelatedAccount, AccountBalance, Account
from .allergy_intolerance import AllergyIntoleranceParticipant, AllergyIntoleranceReaction, AllergyIntolerance
from .encounter import EncounterParticipant, EncounterReason, EncounterDiagnosis, EncounterAdmission, EncounterLocation, Encounter
from .research_study import ResearchStudyLabel, ResearchStudyAssociatedParty, ResearchStudyProgressStatus, ResearchStudyRecruitment, ResearchStudyComparisonGroup, ResearchStudyObjective, ResearchStudyOutcomeMeasure, ResearchStudy
from .biologically_derived_product import BiologicallyDerivedProductCollection, BiologicallyDerivedProductProperty, BiologicallyDerivedProduct
from .medication_dispense import MedicationDispensePerformer, MedicationDispenseSubstitution, MedicationDispense
from .nutrition_order import NutritionOrderOralDietSchedule, NutritionOrderOralDietNutrient, NutritionOrderOralDietTexture, NutritionOrderOralDiet, NutritionOrderSupplementSchedule, NutritionOrderSupplement, NutritionOrderEnteralFormulaAdditive, NutritionOrderEnteralFormulaAdministrationSchedule, NutritionOrderEnteralFormulaAdministration, NutritionOrderEnteralFormula, NutritionOrder
from .operation_outcome import OperationOutcomeIssue, OperationOutcome
from .observation import ObservationTriggeredBy, ObservationReferenceRange, ObservationComponent, Observation
from .slot import Slot
from .implementation_guide import ImplementationGuideDependsOn, ImplementationGuideGlobal, ImplementationGuideDefinitionGrouping, ImplementationGuideDefinitionResource, ImplementationGuideDefinitionPage, ImplementationGuideDefinitionParameter, ImplementationGuideDefinitionTemplate, ImplementationGuideDefinition, ImplementationGuideManifestResource, ImplementationGuideManifestPage, ImplementationGuideManifest, ImplementationGuide
from .device_request import DeviceRequestParameter, DeviceRequest
from .device_association import DeviceAssociationOperation, DeviceAssociation
from .measure_report import MeasureReportGroupPopulation, MeasureReportGroupStratifierStratumComponent, MeasureReportGroupStratifierStratumPopulation, MeasureReportGroupStratifierStratum, MeasureReportGroupStratifier, MeasureReportGroup, MeasureReport
from .linkage import LinkageItem, Linkage
from .binary import Binary
from .domain_resource import DomainResource
from .plan_definition import PlanDefinitionGoalTarget, PlanDefinitionGoal, PlanDefinitionActorOption, PlanDefinitionActor, PlanDefinitionActionCondition, PlanDefinitionActionInput, PlanDefinitionActionOutput, PlanDefinitionActionRelatedAction, PlanDefinitionActionParticipant, PlanDefinitionActionDynamicValue, PlanDefinitionAction, PlanDefinition
from .invoice import InvoiceParticipant, InvoiceLineItem, Invoice
from .goal import GoalTarget, Goal
from .coverage import CoveragePaymentBy, CoverageClass, CoverageCostToBeneficiaryException, CoverageCostToBeneficiary, Coverage
from .audit_event import AuditEventOutcome, AuditEventAgent, AuditEventSource, AuditEventEntityDetail, AuditEventEntity, AuditEvent
from .genomic_study import GenomicStudyAnalysisInput, GenomicStudyAnalysisOutput, GenomicStudyAnalysisPerformer, GenomicStudyAnalysisDevice, GenomicStudyAnalysis, GenomicStudy
from .bundle import BundleLink, BundleEntrySearch, BundleEntryRequest, BundleEntryResponse, BundleEntry, Bundle
from .payment_notice import PaymentNotice
from .location import LocationPosition, Location
from .inventory_report import InventoryReportInventoryListingItem, InventoryReportInventoryListing, InventoryReport
from .care_plan import CarePlanActivity, CarePlan
from .parameters import ParametersParameter, Parameters
from .appointment import AppointmentParticipant, AppointmentRecurrenceTemplateWeeklyTemplate, AppointmentRecurrenceTemplateMonthlyTemplate, AppointmentRecurrenceTemplateYearlyTemplate, AppointmentRecurrenceTemplate, Appointment
from .organization import OrganizationQualification, Organization
from .basic import Basic
from .charge_item import ChargeItemPerformer, ChargeItem
from .procedure import ProcedurePerformer, ProcedureFocalDevice, Procedure
from .packaged_product_definition import PackagedProductDefinitionLegalStatusOfSupply, PackagedProductDefinitionPackagingProperty, PackagedProductDefinitionPackagingContainedItem, PackagedProductDefinitionPackaging, PackagedProductDefinition
from .substance import SubstanceIngredient, Substance
from .library import Library
from .device_metric import DeviceMetricCalibration, DeviceMetric

__all__ = [
    "GroupCharacteristic",
    "GroupMember",
    "Group",
    "ActivityDefinitionParticipant",
    "ActivityDefinitionDynamicValue",
    "ActivityDefinition",
    "Flag",
    "EventDefinition",
    "ArtifactAssessmentContent",
    "ArtifactAssessment",
    "HealthcareServiceEligibility",
    "HealthcareService",
    "SubscriptionFilterBy",
    "SubscriptionParameter",
    "Subscription",
    "SearchParameterComponent",
    "SearchParameter",
    "ClinicalUseDefinitionContraindicationOtherTherapy",
    "ClinicalUseDefinitionContraindication",
    "ClinicalUseDefinitionIndication",
    "ClinicalUseDefinitionInteractionInteractant",
    "ClinicalUseDefinitionInteraction",
    "ClinicalUseDefinitionUndesirableEffect",
    "ClinicalUseDefinitionWarning",
    "ClinicalUseDefinition",
    "BodyStructureIncludedStructureBodyLandmarkOrientationDistanceFromLandmark",
    "BodyStructureIncludedStructureBodyLandmarkOrientation",
    "BodyStructureIncludedStructure",
    "BodyStructure",
    "GraphDefinitionNode",
    "GraphDefinitionLinkCompartment",
    "GraphDefinitionLink",
    "GraphDefinition",
    "TerminologyCapabilitiesSoftware",
    "TerminologyCapabilitiesImplementation",
    "TerminologyCapabilitiesCodeSystemVersionFilter",
    "TerminologyCapabilitiesCodeSystemVersion",
    "TerminologyCapabilitiesCodeSystem",
    "TerminologyCapabilitiesExpansionParameter",
    "TerminologyCapabilitiesExpansion",
    "TerminologyCapabilitiesValidateCode",
    "TerminologyCapabilitiesTranslation",
    "TerminologyCapabilitiesClosure",
    "TerminologyCapabilities",
    "PractitionerRole",
    "CapabilityStatementSoftware",
    "CapabilityStatementImplementation",
    "CapabilityStatementRestSecurity",
    "CapabilityStatementRestResourceInteraction",
    "CapabilityStatementRestResourceSearchParam",
    "CapabilityStatementRestResourceOperation",
    "CapabilityStatementRestResource",
    "CapabilityStatementRestInteraction",
    "CapabilityStatementRest",
    "CapabilityStatementMessagingEndpoint",
    "CapabilityStatementMessagingSupportedMessage",
    "CapabilityStatementMessaging",
    "CapabilityStatementDocument",
    "CapabilityStatement",
    "SubstancePolymerMonomerSetStartingMaterial",
    "SubstancePolymerMonomerSet",
    "SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation",
    "SubstancePolymerRepeatRepeatUnitStructuralRepresentation",
    "SubstancePolymerRepeatRepeatUnit",
    "SubstancePolymerRepeat",
    "SubstancePolymer",
    "ConceptMapProperty",
    "ConceptMapAdditionalAttribute",
    "ConceptMapGroupElementTargetProperty",
    "ConceptMapGroupElementTargetDependsOn",
    "ConceptMapGroupElementTarget",
    "ConceptMapGroupElement",
    "ConceptMapGroupUnmapped",
    "ConceptMapGroup",
    "ConceptMap",
    "ListEntry",
    "List",
    "NutritionIntakeConsumedItem",
    "NutritionIntakeIngredientLabel",
    "NutritionIntakePerformer",
    "NutritionIntake",
    "CommunicationPayload",
    "Communication",
    "MetadataResource",
    "ValueSetComposeIncludeConceptDesignation",
    "ValueSetComposeIncludeConcept",
    "ValueSetComposeIncludeFilter",
    "ValueSetComposeInclude",
    "ValueSetCompose",
    "ValueSetExpansionParameter",
    "ValueSetExpansionProperty",
    "ValueSetExpansionContainsPropertySubProperty",
    "ValueSetExpansionContainsProperty",
    "ValueSetExpansionContains",
    "ValueSetExpansion",
    "ValueSetScope",
    "ValueSet",
    "ProvenanceAgent",
    "ProvenanceEntity",
    "Provenance",
    "ClaimResponseEvent",
    "ClaimResponseItemReviewOutcome",
    "ClaimResponseItemAdjudication",
    "ClaimResponseItemDetailSubDetail",
    "ClaimResponseItemDetail",
    "ClaimResponseItem",
    "ClaimResponseAddItemBodySite",
    "ClaimResponseAddItemDetailSubDetail",
    "ClaimResponseAddItemDetail",
    "ClaimResponseAddItem",
    "ClaimResponseTotal",
    "ClaimResponsePayment",
    "ClaimResponseProcessNote",
    "ClaimResponseInsurance",
    "ClaimResponseError",
    "ClaimResponse",
    "ObservationDefinitionQualifiedValue",
    "ObservationDefinitionComponent",
    "ObservationDefinition",
    "FamilyMemberHistoryParticipant",
    "FamilyMemberHistoryCondition",
    "FamilyMemberHistoryProcedure",
    "FamilyMemberHistory",
    "EvidenceReportSubjectCharacteristic",
    "EvidenceReportSubject",
    "EvidenceReportRelatesToTarget",
    "EvidenceReportRelatesTo",
    "EvidenceReportSection",
    "EvidenceReport",
    "MedicationRequestDispenseRequestInitialFill",
    "MedicationRequestDispenseRequest",
    "MedicationRequestSubstitution",
    "MedicationRequest",
    "ManufacturedItemDefinitionProperty",
    "ManufacturedItemDefinitionComponentConstituent",
    "ManufacturedItemDefinitionComponent",
    "ManufacturedItemDefinition",
    "TestScriptOrigin",
    "TestScriptDestination",
    "TestScriptMetadataLink",
    "TestScriptMetadataCapability",
    "TestScriptMetadata",
    "TestScriptScope",
    "TestScriptFixture",
    "TestScriptVariable",
    "TestScriptSetupActionOperationRequestHeader",
    "TestScriptSetupActionOperation",
    "TestScriptSetupActionAssertRequirement",
    "TestScriptSetupActionAssert",
    "TestScriptSetupAction",
    "TestScriptSetup",
    "TestScriptTestAction",
    "TestScriptTest",
    "TestScriptTeardownAction",
    "TestScriptTeardown",
    "TestScript",
    "AdministrableProductDefinitionProperty",
    "AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod",
    "AdministrableProductDefinitionRouteOfAdministrationTargetSpecies",
    "AdministrableProductDefinitionRouteOfAdministration",
    "AdministrableProductDefinition",
    "TestPlanDependency",
    "TestPlanTestCaseDependency",
    "TestPlanTestCaseTestRunScript",
    "TestPlanTestCaseTestRun",
    "TestPlanTestCaseTestData",
    "TestPlanTestCaseAssertion",
    "TestPlanTestCase",
    "TestPlan",
    "EnrollmentResponse",
    "ConditionParticipant",
    "ConditionStage",
    "Condition",
    "SpecimenFeature",
    "SpecimenCollection",
    "SpecimenProcessing",
    "SpecimenContainer",
    "Specimen",
    "MessageDefinitionFocus",
    "MessageDefinitionAllowedResponse",
    "MessageDefinition",
    "CitationSummary",
    "CitationClassification",
    "CitationStatusDate",
    "CitationCitedArtifactVersion",
    "CitationCitedArtifactStatusDate",
    "CitationCitedArtifactTitle",
    "CitationCitedArtifactAbstract",
    "CitationCitedArtifactPart",
    "CitationCitedArtifactRelatesTo",
    "CitationCitedArtifactPublicationFormPublishedIn",
    "CitationCitedArtifactPublicationForm",
    "CitationCitedArtifactWebLocation",
    "CitationCitedArtifactClassification",
    "CitationCitedArtifactContributorshipEntryContributionInstance",
    "CitationCitedArtifactContributorshipEntry",
    "CitationCitedArtifactContributorshipSummary",
    "CitationCitedArtifactContributorship",
    "CitationCitedArtifact",
    "Citation",
    "RegulatedAuthorizationCase",
    "RegulatedAuthorization",
    "PermissionJustification",
    "PermissionRuleDataResource",
    "PermissionRuleData",
    "PermissionRuleActivity",
    "PermissionRule",
    "Permission",
    "StructureDefinitionMapping",
    "StructureDefinitionContext",
    "StructureDefinitionSnapshot",
    "StructureDefinitionDifferential",
    "StructureDefinition",
    "VerificationResultPrimarySource",
    "VerificationResultAttestation",
    "VerificationResultValidator",
    "VerificationResult",
    "DeviceDispensePerformer",
    "DeviceDispense",
    "EvidenceVariableDefinition",
    "EvidenceStatisticSampleSize",
    "EvidenceStatisticAttributeEstimate",
    "EvidenceStatisticModelCharacteristicVariable",
    "EvidenceStatisticModelCharacteristic",
    "EvidenceStatistic",
    "EvidenceCertainty",
    "Evidence",
    "DeviceDefinitionUdiDeviceIdentifierMarketDistribution",
    "DeviceDefinitionUdiDeviceIdentifier",
    "DeviceDefinitionRegulatoryIdentifier",
    "DeviceDefinitionDeviceName",
    "DeviceDefinitionClassification",
    "DeviceDefinitionConformsTo",
    "DeviceDefinitionHasPart",
    "DeviceDefinitionPackagingDistributor",
    "DeviceDefinitionPackaging",
    "DeviceDefinitionVersion",
    "DeviceDefinitionProperty",
    "DeviceDefinitionLink",
    "DeviceDefinitionMaterial",
    "DeviceDefinitionGuideline",
    "DeviceDefinitionCorrectiveAction",
    "DeviceDefinitionChargeItem",
    "DeviceDefinition",
    "RequirementsStatement",
    "Requirements",
    "DeviceUdiCarrier",
    "DeviceName",
    "DeviceVersion",
    "DeviceConformsTo",
    "DeviceProperty",
    "Device",
    "FormularyItem",
    "ConditionDefinitionObservation",
    "ConditionDefinitionMedication",
    "ConditionDefinitionPrecondition",
    "ConditionDefinitionQuestionnaire",
    "ConditionDefinitionPlan",
    "ConditionDefinition",
    "SpecimenDefinitionTypeTestedContainerAdditive",
    "SpecimenDefinitionTypeTestedContainer",
    "SpecimenDefinitionTypeTestedHandling",
    "SpecimenDefinitionTypeTested",
    "SpecimenDefinition",
    "AdverseEventParticipant",
    "AdverseEventSuspectEntityCausality",
    "AdverseEventSuspectEntity",
    "AdverseEventContributingFactor",
    "AdverseEventPreventiveAction",
    "AdverseEventMitigatingAction",
    "AdverseEventSupportingInfo",
    "AdverseEvent",
    "AppointmentResponse",
    "NutritionProductNutrient",
    "NutritionProductIngredient",
    "NutritionProductCharacteristic",
    "NutritionProductInstance",
    "NutritionProduct",
    "PractitionerQualification",
    "PractitionerCommunication",
    "Practitioner",
    "SubstanceDefinitionMoiety",
    "SubstanceDefinitionCharacterization",
    "SubstanceDefinitionProperty",
    "SubstanceDefinitionMolecularWeight",
    "SubstanceDefinitionStructureRepresentation",
    "SubstanceDefinitionStructure",
    "SubstanceDefinitionCode",
    "SubstanceDefinitionNameOfficial",
    "SubstanceDefinitionName",
    "SubstanceDefinitionRelationship",
    "SubstanceDefinitionSourceMaterial",
    "SubstanceDefinition",
    "ClinicalImpressionFinding",
    "ClinicalImpression",
    "PatientContact",
    "PatientCommunication",
    "PatientLink",
    "Patient",
    "InventoryItemName",
    "InventoryItemResponsibleOrganization",
    "InventoryItemDescription",
    "InventoryItemAssociation",
    "InventoryItemCharacteristic",
    "InventoryItemInstance",
    "InventoryItem",
    "ImmunizationPerformer",
    "ImmunizationProgramEligibility",
    "ImmunizationReaction",
    "ImmunizationProtocolApplied",
    "Immunization",
    "SubscriptionTopicResourceTriggerQueryCriteria",
    "SubscriptionTopicResourceTrigger",
    "SubscriptionTopicEventTrigger",
    "SubscriptionTopicCanFilterBy",
    "SubscriptionTopicNotificationShape",
    "SubscriptionTopic",
    "MedicationKnowledgeRelatedMedicationKnowledge",
    "MedicationKnowledgeMonograph",
    "MedicationKnowledgeCost",
    "MedicationKnowledgeMonitoringProgram",
    "MedicationKnowledgeIndicationGuidelineDosingGuidelineDosage",
    "MedicationKnowledgeIndicationGuidelineDosingGuidelinePatientCharacteristic",
    "MedicationKnowledgeIndicationGuidelineDosingGuideline",
    "MedicationKnowledgeIndicationGuideline",
    "MedicationKnowledgeMedicineClassification",
    "MedicationKnowledgePackaging",
    "MedicationKnowledgeStorageGuidelineEnvironmentalSetting",
    "MedicationKnowledgeStorageGuideline",
    "MedicationKnowledgeRegulatorySubstitution",
    "MedicationKnowledgeRegulatoryMaxDispense",
    "MedicationKnowledgeRegulatory",
    "MedicationKnowledgeDefinitionalIngredient",
    "MedicationKnowledgeDefinitionalDrugCharacteristic",
    "MedicationKnowledgeDefinitional",
    "MedicationKnowledge",
    "TransportRestriction",
    "TransportInput",
    "TransportOutput",
    "Transport",
    "EpisodeOfCareStatusHistory",
    "EpisodeOfCareReason",
    "EpisodeOfCareDiagnosis",
    "EpisodeOfCare",
    "CompositionAttester",
    "CompositionEvent",
    "CompositionSection",
    "Composition",
    "SubstanceNucleicAcidSubunitLinkage",
    "SubstanceNucleicAcidSubunitSugar",
    "SubstanceNucleicAcidSubunit",
    "SubstanceNucleicAcid",
    "NamingSystemUniqueId",
    "NamingSystem",
    "RequestOrchestrationActionCondition",
    "RequestOrchestrationActionInput",
    "RequestOrchestrationActionOutput",
    "RequestOrchestrationActionRelatedAction",
    "RequestOrchestrationActionParticipant",
    "RequestOrchestrationActionDynamicValue",
    "RequestOrchestrationAction",
    "RequestOrchestration",
    "ActorDefinition",
    "BiologicallyDerivedProductDispensePerformer",
    "BiologicallyDerivedProductDispense",
    "ContractContentDefinition",
    "ContractTermSecurityLabel",
    "ContractTermOfferParty",
    "ContractTermOfferAnswer",
    "ContractTermOffer",
    "ContractTermAssetContext",
    "ContractTermAssetValuedItem",
    "ContractTermAsset",
    "ContractTermActionSubject",
    "ContractTermAction",
    "ContractTerm",
    "ContractSigner",
    "ContractFriendly",
    "ContractLegal",
    "ContractRule",
    "Contract",
    "ConsentPolicyBasis",
    "ConsentVerification",
    "ConsentProvisionActor",
    "ConsentProvisionData",
    "ConsentProvision",
    "Consent",
    "SubscriptionStatusNotificationEvent",
    "SubscriptionStatus",
    "SubstanceSourceMaterialFractionDescription",
    "SubstanceSourceMaterialOrganismAuthor",
    "SubstanceSourceMaterialOrganismHybrid",
    "SubstanceSourceMaterialOrganismOrganismGeneral",
    "SubstanceSourceMaterialOrganism",
    "SubstanceSourceMaterialPartDescription",
    "SubstanceSourceMaterial",
    "ExampleScenarioActor",
    "ExampleScenarioInstanceVersion",
    "ExampleScenarioInstanceContainedInstance",
    "ExampleScenarioInstance",
    "ExampleScenarioProcessStepOperation",
    "ExampleScenarioProcessStepAlternative",
    "ExampleScenarioProcessStep",
    "ExampleScenarioProcess",
    "ExampleScenario",
    "EvidenceVariableCharacteristicDefinitionByTypeAndValue",
    "EvidenceVariableCharacteristicDefinitionByCombination",
    "EvidenceVariableCharacteristicTimeFromEvent",
    "EvidenceVariableCharacteristic",
    "EvidenceVariableCategory",
    "EvidenceVariable",
    "TestReportParticipant",
    "TestReportSetupActionOperation",
    "TestReportSetupActionAssertRequirement",
    "TestReportSetupActionAssert",
    "TestReportSetupAction",
    "TestReportSetup",
    "TestReportTestAction",
    "TestReportTest",
    "TestReportTeardownAction",
    "TestReportTeardown",
    "TestReport",
    "CanonicalResource",
    "DeviceUsageAdherence",
    "DeviceUsage",
    "ClaimRelated",
    "ClaimPayee",
    "ClaimEvent",
    "ClaimCareTeam",
    "ClaimSupportingInfo",
    "ClaimDiagnosis",
    "ClaimProcedure",
    "ClaimInsurance",
    "ClaimAccident",
    "ClaimItemBodySite",
    "ClaimItemDetailSubDetail",
    "ClaimItemDetail",
    "ClaimItem",
    "Claim",
    "QuestionnaireItemEnableWhen",
    "QuestionnaireItemAnswerOption",
    "QuestionnaireItemInitial",
    "QuestionnaireItem",
    "Questionnaire",
    "VisionPrescriptionLensSpecificationPrism",
    "VisionPrescriptionLensSpecification",
    "VisionPrescription",
    "RiskAssessmentPrediction",
    "RiskAssessment",
    "ChargeItemDefinitionApplicability",
    "ChargeItemDefinitionPropertyGroup",
    "ChargeItemDefinition",
    "PaymentReconciliationAllocation",
    "PaymentReconciliationProcessNote",
    "PaymentReconciliation",
    "GuidanceResponse",
    "TaskPerformer",
    "TaskRestriction",
    "TaskInput",
    "TaskOutput",
    "Task",
    "IngredientManufacturer",
    "IngredientSubstanceStrengthReferenceStrength",
    "IngredientSubstanceStrength",
    "IngredientSubstance",
    "Ingredient",
    "CoverageEligibilityRequestEvent",
    "CoverageEligibilityRequestSupportingInfo",
    "CoverageEligibilityRequestInsurance",
    "CoverageEligibilityRequestItemDiagnosis",
    "CoverageEligibilityRequestItem",
    "CoverageEligibilityRequest",
    "EnrollmentRequest",
    "StructureMapStructure",
    "StructureMapConst",
    "StructureMapGroupInput",
    "StructureMapGroupRuleSource",
    "StructureMapGroupRuleTargetParameter",
    "StructureMapGroupRuleTarget",
    "StructureMapGroupRuleDependent",
    "StructureMapGroupRule",
    "StructureMapGroup",
    "StructureMap",
    "MedicinalProductDefinitionContact",
    "MedicinalProductDefinitionNamePart",
    "MedicinalProductDefinitionNameUsage",
    "MedicinalProductDefinitionName",
    "MedicinalProductDefinitionCrossReference",
    "MedicinalProductDefinitionOperation",
    "MedicinalProductDefinitionCharacteristic",
    "MedicinalProductDefinition",
    "ImmunizationEvaluation",
    "ImagingStudySeriesPerformer",
    "ImagingStudySeriesInstance",
    "ImagingStudySeries",
    "ImagingStudy",
    "MessageHeaderDestination",
    "MessageHeaderSource",
    "MessageHeaderResponse",
    "MessageHeader",
    "ExplanationOfBenefitRelated",
    "ExplanationOfBenefitEvent",
    "ExplanationOfBenefitPayee",
    "ExplanationOfBenefitCareTeam",
    "ExplanationOfBenefitSupportingInfo",
    "ExplanationOfBenefitDiagnosis",
    "ExplanationOfBenefitProcedure",
    "ExplanationOfBenefitInsurance",
    "ExplanationOfBenefitAccident",
    "ExplanationOfBenefitItemBodySite",
    "ExplanationOfBenefitItemReviewOutcome",
    "ExplanationOfBenefitItemAdjudication",
    "ExplanationOfBenefitItemDetailSubDetail",
    "ExplanationOfBenefitItemDetail",
    "ExplanationOfBenefitItem",
    "ExplanationOfBenefitAddItemBodySite",
    "ExplanationOfBenefitAddItemDetailSubDetail",
    "ExplanationOfBenefitAddItemDetail",
    "ExplanationOfBenefitAddItem",
    "ExplanationOfBenefitTotal",
    "ExplanationOfBenefitPayment",
    "ExplanationOfBenefitProcessNote",
    "ExplanationOfBenefitBenefitBalanceFinancial",
    "ExplanationOfBenefitBenefitBalance",
    "ExplanationOfBenefit",
    "SupplyRequestParameter",
    "SupplyRequest",
    "ImmunizationRecommendationRecommendationDateCriterion",
    "ImmunizationRecommendationRecommendation",
    "ImmunizationRecommendation",
    "SubstanceProteinSubunit",
    "SubstanceProtein",
    "CoverageEligibilityResponseEvent",
    "CoverageEligibilityResponseInsuranceItemBenefit",
    "CoverageEligibilityResponseInsuranceItem",
    "CoverageEligibilityResponseInsurance",
    "CoverageEligibilityResponseError",
    "CoverageEligibilityResponse",
    "RelatedPersonCommunication",
    "RelatedPerson",
    "ImagingSelectionPerformer",
    "ImagingSelectionInstanceImageRegion2D",
    "ImagingSelectionInstanceImageRegion3D",
    "ImagingSelectionInstance",
    "ImagingSelection",
    "CommunicationRequestPayload",
    "CommunicationRequest",
    "MolecularSequenceRelativeStartingSequence",
    "MolecularSequenceRelativeEdit",
    "MolecularSequenceRelative",
    "MolecularSequence",
    "InsurancePlanCoverageBenefitLimit",
    "InsurancePlanCoverageBenefit",
    "InsurancePlanCoverage",
    "InsurancePlanPlanGeneralCost",
    "InsurancePlanPlanSpecificCostBenefitCost",
    "InsurancePlanPlanSpecificCostBenefit",
    "InsurancePlanPlanSpecificCost",
    "InsurancePlanPlan",
    "InsurancePlan",
    "MedicationIngredient",
    "MedicationBatch",
    "Medication",
    "CareTeamParticipant",
    "CareTeam",
    "OperationDefinitionParameterBinding",
    "OperationDefinitionParameterReferencedFrom",
    "OperationDefinitionParameter",
    "OperationDefinitionOverload",
    "OperationDefinition",
    "PersonCommunication",
    "PersonLink",
    "Person",
    "SubstanceReferenceInformationGene",
    "SubstanceReferenceInformationGeneElement",
    "SubstanceReferenceInformationTarget",
    "SubstanceReferenceInformation",
    "DiagnosticReportSupportingInfo",
    "DiagnosticReportMedia",
    "DiagnosticReport",
    "EncounterHistoryLocation",
    "EncounterHistory",
    "CompartmentDefinitionResource",
    "CompartmentDefinition",
    "ServiceRequestOrderDetailParameter",
    "ServiceRequestOrderDetail",
    "ServiceRequestPatientInstruction",
    "ServiceRequest",
    "MedicationAdministrationPerformer",
    "MedicationAdministrationDosage",
    "MedicationAdministration",
    "CodeSystemFilter",
    "CodeSystemProperty",
    "CodeSystemConceptDesignation",
    "CodeSystemConceptProperty",
    "CodeSystemConcept",
    "CodeSystem",
    "DetectedIssueEvidence",
    "DetectedIssueMitigation",
    "DetectedIssue",
    "QuestionnaireResponseItemAnswer",
    "QuestionnaireResponseItem",
    "QuestionnaireResponse",
    "EndpointPayload",
    "Endpoint",
    "MeasureTerm",
    "MeasureGroupPopulation",
    "MeasureGroupStratifierComponent",
    "MeasureGroupStratifier",
    "MeasureGroup",
    "MeasureSupplementalData",
    "Measure",
    "Resource",
    "SupplyDeliverySuppliedItem",
    "SupplyDelivery",
    "ResearchSubjectProgress",
    "ResearchSubject",
    "OrganizationAffiliation",
    "MedicationStatementAdherence",
    "MedicationStatement",
    "DocumentReferenceAttester",
    "DocumentReferenceRelatesTo",
    "DocumentReferenceContentProfile",
    "DocumentReferenceContent",
    "DocumentReference",
    "Schedule",
    "AccountCoverage",
    "AccountGuarantor",
    "AccountDiagnosis",
    "AccountProcedure",
    "AccountRelatedAccount",
    "AccountBalance",
    "Account",
    "AllergyIntoleranceParticipant",
    "AllergyIntoleranceReaction",
    "AllergyIntolerance",
    "EncounterParticipant",
    "EncounterReason",
    "EncounterDiagnosis",
    "EncounterAdmission",
    "EncounterLocation",
    "Encounter",
    "ResearchStudyLabel",
    "ResearchStudyAssociatedParty",
    "ResearchStudyProgressStatus",
    "ResearchStudyRecruitment",
    "ResearchStudyComparisonGroup",
    "ResearchStudyObjective",
    "ResearchStudyOutcomeMeasure",
    "ResearchStudy",
    "BiologicallyDerivedProductCollection",
    "BiologicallyDerivedProductProperty",
    "BiologicallyDerivedProduct",
    "MedicationDispensePerformer",
    "MedicationDispenseSubstitution",
    "MedicationDispense",
    "NutritionOrderOralDietSchedule",
    "NutritionOrderOralDietNutrient",
    "NutritionOrderOralDietTexture",
    "NutritionOrderOralDiet",
    "NutritionOrderSupplementSchedule",
    "NutritionOrderSupplement",
    "NutritionOrderEnteralFormulaAdditive",
    "NutritionOrderEnteralFormulaAdministrationSchedule",
    "NutritionOrderEnteralFormulaAdministration",
    "NutritionOrderEnteralFormula",
    "NutritionOrder",
    "OperationOutcomeIssue",
    "OperationOutcome",
    "ObservationTriggeredBy",
    "ObservationReferenceRange",
    "ObservationComponent",
    "Observation",
    "Slot",
    "ImplementationGuideDependsOn",
    "ImplementationGuideGlobal",
    "ImplementationGuideDefinitionGrouping",
    "ImplementationGuideDefinitionResource",
    "ImplementationGuideDefinitionPage",
    "ImplementationGuideDefinitionParameter",
    "ImplementationGuideDefinitionTemplate",
    "ImplementationGuideDefinition",
    "ImplementationGuideManifestResource",
    "ImplementationGuideManifestPage",
    "ImplementationGuideManifest",
    "ImplementationGuide",
    "DeviceRequestParameter",
    "DeviceRequest",
    "DeviceAssociationOperation",
    "DeviceAssociation",
    "MeasureReportGroupPopulation",
    "MeasureReportGroupStratifierStratumComponent",
    "MeasureReportGroupStratifierStratumPopulation",
    "MeasureReportGroupStratifierStratum",
    "MeasureReportGroupStratifier",
    "MeasureReportGroup",
    "MeasureReport",
    "LinkageItem",
    "Linkage",
    "Binary",
    "DomainResource",
    "PlanDefinitionGoalTarget",
    "PlanDefinitionGoal",
    "PlanDefinitionActorOption",
    "PlanDefinitionActor",
    "PlanDefinitionActionCondition",
    "PlanDefinitionActionInput",
    "PlanDefinitionActionOutput",
    "PlanDefinitionActionRelatedAction",
    "PlanDefinitionActionParticipant",
    "PlanDefinitionActionDynamicValue",
    "PlanDefinitionAction",
    "PlanDefinition",
    "InvoiceParticipant",
    "InvoiceLineItem",
    "Invoice",
    "GoalTarget",
    "Goal",
    "CoveragePaymentBy",
    "CoverageClass",
    "CoverageCostToBeneficiaryException",
    "CoverageCostToBeneficiary",
    "Coverage",
    "AuditEventOutcome",
    "AuditEventAgent",
    "AuditEventSource",
    "AuditEventEntityDetail",
    "AuditEventEntity",
    "AuditEvent",
    "GenomicStudyAnalysisInput",
    "GenomicStudyAnalysisOutput",
    "GenomicStudyAnalysisPerformer",
    "GenomicStudyAnalysisDevice",
    "GenomicStudyAnalysis",
    "GenomicStudy",
    "BundleLink",
    "BundleEntrySearch",
    "BundleEntryRequest",
    "BundleEntryResponse",
    "BundleEntry",
    "Bundle",
    "PaymentNotice",
    "LocationPosition",
    "Location",
    "InventoryReportInventoryListingItem",
    "InventoryReportInventoryListing",
    "InventoryReport",
    "CarePlanActivity",
    "CarePlan",
    "ParametersParameter",
    "Parameters",
    "AppointmentParticipant",
    "AppointmentRecurrenceTemplateWeeklyTemplate",
    "AppointmentRecurrenceTemplateMonthlyTemplate",
    "AppointmentRecurrenceTemplateYearlyTemplate",
    "AppointmentRecurrenceTemplate",
    "Appointment",
    "OrganizationQualification",
    "Organization",
    "Basic",
    "ChargeItemPerformer",
    "ChargeItem",
    "ProcedurePerformer",
    "ProcedureFocalDevice",
    "Procedure",
    "PackagedProductDefinitionLegalStatusOfSupply",
    "PackagedProductDefinitionPackagingProperty",
    "PackagedProductDefinitionPackagingContainedItem",
    "PackagedProductDefinitionPackaging",
    "PackagedProductDefinition",
    "SubstanceIngredient",
    "Substance",
    "Library",
    "DeviceMetricCalibration",
    "DeviceMetric",
]
