[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "fhircraft/__init__.py"

[project]
name = 'fhircraft'
dynamic = ["version"]
description = "Fhircraft transforms FHIR (Fast Healthcare Interoperability Resources) specifications into type-safe Python models using Pydantic. Build healthcare applications with automatic validation, intelligent code completion, and seamless integration with Python's ecosystem."
authors = [
    {name = 'Luis Fábregas-Ibáñez', email = 'luisfabib@gmail.com'},
]
keywords = ["Pydantic", "FHIR", "healthcare", "modelling", "validation"]
license = 'MIT'
license-files = ['LICENSE']
classifiers = [
    'Development Status :: 4 - Beta',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Intended Audience :: Developers',
    'Intended Audience :: Information Technology',
    'Intended Audience :: Healthcare Industry',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: MIT License',
    'Operating System :: Unix',
    'Operating System :: POSIX :: Linux',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: OS Independent',
    'Environment :: Console',
    'Framework :: Pydantic',
    'Framework :: Pydantic :: 2',
    'Topic :: Software Development :: Libraries :: Python Modules',
]
requires-python = '>=3.11'
readme = "README.md"
dependencies = [
    'requests>=2.28',
    'pydantic>=2.7',
    'pydantic_core>=2.18',
    'ply>=3.11',
    'pyyaml>=6.0.1',
    'python-dotenv>=1.0',
    'jsonschema>=4',
    'jsonpath-ng>=1',
    'jinja2>=3.1',
    'Pint>=0.24',
    'packaging>=25',
    'typing_extensions>=4.6.0',
]

[project.urls]
Homepage = "https://github.com/luisfabib/fhircraft"
Issues = "https://github.com/luisfabib/fhircraft/issues"
Documentation = "https://luisfabib.github.io/fhircraft/"
Changelog = "https://github.com/luisfabib/fhircraft/blob/main/CHANGELOG.md"


[project.optional-dependencies]
dev = [
    "pytest>=8.2",
    "pytest-mock>=3.14.0",
    "parameterized>=0.9.0",
    "coverage>=7.5.1",
]
docs = [
    "zensical>=0.0.47",   
    "mkdocstrings-python>=1.13.0",
    "markdown-exec[ansi]>=1.12.3",
    "griffe-fieldz==0.4.0",
]

[tool.hatch.build.targets.sdist]
include = [
    'pyproject.toml',
    'README.md',
    'CHANGELOG.md',
    'LICENSE',
    '/fhircraft',
    '/test',
]

[tool.pytest.ini_options]
python_files = [
    "**/test/test_*.py",
]
markers = [
    "integration",
]
testpaths = ['test']
