
[project]
site_name = "Fhircraft - Documentation"
site_description = "A Python library for working with FHIR resources and profiles."
site_author = "Luis Fábregas-Ibáñez"
site_url = "https://luisfabib.github.io/fhircraft/"

repo_url = "https://github.com/luisfabib/fhircraft"
repo_name = "luisfabib/fhircraft"

copyright = """
Copyright &copy; 2024 - 2026 Luis Fábregas-Ibáñez and contributors
"""

# Implicit navigation
nav = [
  { "Home" = "index.md" },
  { "User Guide" = [
    { "Overview" = "user-guide/overview.md" },
    { "First Steps" = [
          { "Installation" = "quickstart/installation.md" },
          { "Quick Start" = "quickstart/quickstart.md" }
    ]},
    { "Fhircraft" = [
        { "Pydantic FHIR" = "user-guide/pydantic-representation.md" },
        { "FHIR Models" = "user-guide/resources-models.md" },
        { "Management" = "user-guide/managing-fhir-artifacts.md" },
        { "Factory" = "user-guide/resources-construction.md" },
        { "Configuration" = "user-guide/configuration.md" },
        { "FHIRPath" = "user-guide/fhirpath.md" },
        { "FHIR Mapping" = "user-guide/mapper.md" },
        { "Error Handling" = "user-guide/error-handling.md" }
    ]},
  ]},
  { "Community" = [
    { "Contributing" = "community/contributing.md" },
    { "Code of Conduct" = "community/code-of-conduct.md" },
    { "Alternatives" = "community/alternatives.md" },
    { "Credits" = "community/credits.md" },
    { "License" = "community/license.md" },
  ]},
  { "Release Notes" = "release-notes.md" },
  { "Reference" = [
    { "FHIR Resources" = [
      { "Base" = "reference/fhir-resources-base.md" },
      { "Factory" = "reference/fhir-resources-factory.md" },
      { "Structure Definitions" = "reference/fhir-resources-definitions.md" },
      { "Code Generator" = "reference/fhir-resources-code-generator.md" },
          { "Built-in Types" = [
              { "R4" = [
                  { "Primitive Types" = "reference/fhir-resources-r4-primitive.md" },
                  { "Complex Types" = "reference/fhir-resources-r4-complex.md" },
                  { "Core Resources" = "reference/fhir-resources-r4-core.md" }
              ]},
              { "R4B" = [
                  { "Primitive Types" = "reference/fhir-resources-r4b-primitive.md" },
                  { "Complex Types" = "reference/fhir-resources-r4b-complex.md" },
                  { "Core Resources" = "reference/fhir-resources-r4b-core.md" }
              ]},
              { "R5" = [
                  { "Primitive Types" = "reference/fhir-resources-r5-primitive.md" },
                  { "Complex Types" = "reference/fhir-resources-r5-complex.md" },
                  { "Core Resources" = "reference/fhir-resources-r5-core.md" }
              ]},
              { "Registries" = "reference/fhir-resources-type-registries.md" },
              { "Type Utilities" = "reference/fhir-resources-type-utils.md" },
        ]},
    ]},
    { "FHIRPath" = [
          { "Engine" = "reference/fhir-path-engine.md" },
          { "Mixin" = "reference/fhir-path-mixin.md" },
          { "Parser" = "reference/fhir-path-parser.md" }
    ]},
    { "FHIR Mapping" = [
        { "Engine" = "reference/fhir-mapping-engine.md" },
        { "Parser" = "reference/fhir-mapping-parser.md" }
    ]},
    { "FHIR Package Registry" = [
        { "Client" = "reference/fhir-packages-client.md" },
        { "Models" = "reference/fhir-packages-models.md" }
    ]},
    { "Other" = [
        { "Core Utilities" = "reference/core-utilities.md" },
        { "Exceptions" = "reference/exceptions.md" }
    ]},
  ]}
]

extra_css = [
  "assets/css/extra.css",
  "assets/css/mkdocstrings.css",
]

[project.theme]
favicon = "assets/images/favicon.png"
language = "en"
features = [
    # Zensical includes an announcement bar. This feature allows users to
    # dismiss it when they have read the announcement.
    # https://zensical.org/docs/setup/header/#announcement-bar
    "announce.dismiss",

    # If you have a repository configured and turn on this feature, Zensical
    # will generate an edit button for the page. This works for common
    # repository hosting services.
    # https://zensical.org/docs/setup/repository/#content-actions
    #"content.action.edit",

    # If you have a repository configured and turn on this feature, Zensical
    # will generate a button that allows the user to view the Markdown
    # code for the current page.
    # https://zensical.org/docs/setup/repository/#content-actions
    #"content.action.view",

    # Code annotations allow you to add an icon with a tooltip to your
    # code blocks to provide explanations at crucial points.
    # https://zensical.org/docs/authoring/code-blocks/#code-annotations
    "content.code.annotate",

    # This feature turns on a button in code blocks that allow users to
    # copy the content to their clipboard without first selecting it.
    # https://zensical.org/docs/authoring/code-blocks/#code-copy-button
    "content.code.copy",

    # Code blocks can include a button to allow for the selection of line
    # ranges by the user.
    # https://zensical.org/docs/authoring/code-blocks/#code-selection-button
    "content.code.select",

    # Zensical can render footnotes as inline tooltips, so the user can read
    # the footnote without leaving the context of the document.
    # https://zensical.org/docs/authoring/footnotes/#footnote-tooltips
    "content.footnote.tooltips",

    # If you have many content tabs that have the same titles (e.g., "Python",
    # "JavaScript", "Cobol"), this feature causes all of them to switch to
    # at the same time when the user chooses their language in one.
    # https://zensical.org/docs/authoring/content-tabs/#linked-content-tabs
    "content.tabs.link",

    # With this feature enabled users can add tooltips to links that will be
    # displayed when the mouse pointer hovers the link.
    # https://zensical.org/docs/authoring/tooltips/#improved-tooltips
    "content.tooltips",

    # With this feature enabled, Zensical will automatically hide parts
    # of the header when the user scrolls past a certain point.
    # https://zensical.org/docs/setup/header/#automatic-hiding
    # "header.autohide",

    # Turn on this feature to expand all collapsible sections in the
    # navigation sidebar by default.
    # https://zensical.org/docs/setup/navigation/#navigation-expansion
    # "navigation.expand",

    # This feature turns on navigation elements in the footer that allow the
    # user to navigate to a next or previous page.
    # https://zensical.org/docs/setup/footer/#navigation
    "navigation.footer",

    # When section index pages are enabled, documents can be directly attached
    # to sections, which is particularly useful for providing overview pages.
    # https://zensical.org/docs/setup/navigation/#section-index-pages
    "navigation.indexes",

    # When instant navigation is enabled, clicks on all internal links will be
    # intercepted and dispatched via XHR without fully reloading the page.
    # https://zensical.org/docs/setup/navigation/#instant-navigation
    "navigation.instant",

    # With instant prefetching, your site will start to fetch a page once the
    # user hovers over a link. This will reduce the perceived loading time
    # for the user.
    # https://zensical.org/docs/setup/navigation/#instant-prefetching
    "navigation.instant.prefetch",

    # In order to provide a better user experience on slow connections when
    # using instant navigation, a progress indicator can be enabled.
    # https://zensical.org/docs/setup/navigation/#progress-indicator
    #"navigation.instant.progress",

    # When navigation paths are activated, a breadcrumb navigation is rendered
    # above the title of each page
    # https://zensical.org/docs/setup/navigation/#navigation-path
    "navigation.path",

    # When pruning is enabled, only the visible navigation items are included
    # in the rendered HTML, reducing the size of the built site by 33% or more.
    # https://zensical.org/docs/setup/navigation/#navigation-pruning
    #"navigation.prune",

    # When sections are enabled, top-level sections are rendered as groups in
    # the sidebar for viewports above 1220px, but remain as-is on mobile.
    # https://zensical.org/docs/setup/navigation/#navigation-sections
    "navigation.sections",

    # When tabs are enabled, top-level sections are rendered in a menu layer
    # below the header for viewports above 1220px, but remain as-is on mobile.
    # https://zensical.org/docs/setup/navigation/#navigation-tabs
    "navigation.tabs",

    # When sticky tabs are enabled, navigation tabs will lock below the header
    # and always remain visible when scrolling down.
    # https://zensical.org/docs/setup/navigation/#sticky-navigation-tabs
    "navigation.tabs.sticky",

    # A back-to-top button can be shown when the user, after scrolling down,
    # starts to scroll up again.
    # https://zensical.org/docs/setup/navigation/#back-to-top-button
    "navigation.top",

    # When anchor tracking is enabled, the URL in the address bar is
    # automatically updated with the active anchor as highlighted in the table
    # of contents.
    # https://zensical.org/docs/setup/navigation/#anchor-tracking
    "navigation.tracking",

    # When search highlighting is enabled and a user clicks on a search result,
    # Zensical will highlight all occurrences after following the link.
    # https://zensical.org/docs/setup/search/#search-highlighting
    "search.highlight",

    # When anchor following for the table of contents is enabled, the sidebar
    # is automatically scrolled so that the active anchor is always visible.
    # https://zensical.org/docs/setup/navigation/#anchor-following
    # "toc.follow",

    # When navigation integration for the table of contents is enabled, it is
    # always rendered as part of the navigation sidebar on the left.
    # https://zensical.org/docs/setup/navigation/#navigation-integration
    #"toc.integrate",
]

logo = "assets/images/logo-white.svg"


[project.theme.icon]
repo = "fontawesome/brands/github"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
accent = "red"
primary = "pink"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
accent = "red"
primary = "pink"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
accent = "red"
primary = "pink"

# ----------------------------------------------------------------------------
# Miscellaneous settings.
# ----------------------------------------------------------------------------
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/luisfabib/fhircraft"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/fhircraft/"

[[project.extra.version]]
provider = "mike"
alias = true


# ----------------------------------------------------------------------------
# Markdown extensions
# ----------------------------------------------------------------------------
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]


# ----------------------------------------------------------------------------
# Plugins
# ----------------------------------------------------------------------------

[project.plugins.markdown-exec]


[project.plugins.mkdocstrings]
custom_templates = "docs/.overrides"

[project.plugins.mkdocstrings.handlers.python]
inventories = [
  "https://docs.python.org/3/objects.inv",
  "https://docs.pydantic.dev/latest/objects.inv",
  "https://typing-extensions.readthedocs.io/en/latest/objects.inv"
]
paths = ["fhircraft"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = false
show_source = false
members_order = "source"
separate_signature = true
filters = ["!^_"]
docstring_options.ignore_init_summary = true
merge_init_into_class = true
show_root_heading = true
show_root_full_path = false
show_signature_annotations = true
summary = true
signature_crossrefs = true
extensions = [
  { "griffe_fieldz" = { "include_inherited" = true } }
]

