from .group import GroupCharacteristic, GroupMember, Group
from .activity_definition import ActivityDefinitionParticipant, ActivityDefinitionDynamicValue, ActivityDefinition
from .flag import Flag
from .event_definition import EventDefinition
from .healthcare_service import HealthcareServiceEligibility, HealthcareServiceAvailableTime, HealthcareServiceNotAvailable, HealthcareService
from .subscription import SubscriptionChannel, Subscription
from .search_parameter import SearchParameterComponent, SearchParameter
from .clinical_use_definition import ClinicalUseDefinitionContraindicationOtherTherapy, ClinicalUseDefinitionContraindication, ClinicalUseDefinitionIndication, ClinicalUseDefinitionInteractionInteractant, ClinicalUseDefinitionInteraction, ClinicalUseDefinitionUndesirableEffect, ClinicalUseDefinitionWarning, ClinicalUseDefinition
from .body_structure import BodyStructure
from .graph_definition import GraphDefinitionLinkTargetCompartment, GraphDefinitionLinkTarget, GraphDefinitionLink, GraphDefinition
from .terminology_capabilities import TerminologyCapabilitiesSoftware, TerminologyCapabilitiesImplementation, TerminologyCapabilitiesCodeSystemVersionFilter, TerminologyCapabilitiesCodeSystemVersion, TerminologyCapabilitiesCodeSystem, TerminologyCapabilitiesExpansionParameter, TerminologyCapabilitiesExpansion, TerminologyCapabilitiesValidateCode, TerminologyCapabilitiesTranslation, TerminologyCapabilitiesClosure, TerminologyCapabilities
from .practitioner_role import PractitionerRoleAvailableTime, PractitionerRoleNotAvailable, PractitionerRole
from .capability_statement import CapabilityStatementSoftware, CapabilityStatementImplementation, CapabilityStatementRestSecurity, CapabilityStatementRestResourceInteraction, CapabilityStatementRestResourceSearchParam, CapabilityStatementRestResourceOperation, CapabilityStatementRestResource, CapabilityStatementRestInteraction, CapabilityStatementRest, CapabilityStatementMessagingEndpoint, CapabilityStatementMessagingSupportedMessage, CapabilityStatementMessaging, CapabilityStatementDocument, CapabilityStatement
from .concept_map import ConceptMapGroupElementTargetDependsOn, ConceptMapGroupElementTarget, ConceptMapGroupElement, ConceptMapGroupUnmapped, ConceptMapGroup, ConceptMap
from .list import ListEntry, List
from .communication import CommunicationPayload, Communication
from .research_definition import ResearchDefinition
from .value_set import ValueSetComposeIncludeConceptDesignation, ValueSetComposeIncludeConcept, ValueSetComposeIncludeFilter, ValueSetComposeInclude, ValueSetCompose, ValueSetExpansionParameter, ValueSetExpansionContains, ValueSetExpansion, ValueSet
from .provenance import ProvenanceAgent, ProvenanceEntity, Provenance
from .claim_response import ClaimResponseItemAdjudication, ClaimResponseItemDetailSubDetail, ClaimResponseItemDetail, ClaimResponseItem, ClaimResponseAddItemDetailSubDetail, ClaimResponseAddItemDetail, ClaimResponseAddItem, ClaimResponseTotal, ClaimResponsePayment, ClaimResponseProcessNote, ClaimResponseInsurance, ClaimResponseError, ClaimResponse
from .observation_definition import ObservationDefinitionQuantitativeDetails, ObservationDefinitionQualifiedInterval, ObservationDefinition
from .family_member_history import FamilyMemberHistoryCondition, FamilyMemberHistory
from .evidence_report import EvidenceReportSubjectCharacteristic, EvidenceReportSubject, EvidenceReportRelatesTo, EvidenceReportSection, EvidenceReport
from .medication_request import MedicationRequestDispenseRequestInitialFill, MedicationRequestDispenseRequest, MedicationRequestSubstitution, MedicationRequest
from .manufactured_item_definition import ManufacturedItemDefinitionProperty, ManufacturedItemDefinition
from .test_script import TestScriptOrigin, TestScriptDestination, TestScriptMetadataLink, TestScriptMetadataCapability, TestScriptMetadata, TestScriptFixture, TestScriptVariable, TestScriptSetupActionOperationRequestHeader, TestScriptSetupActionOperation, TestScriptSetupActionAssert, TestScriptSetupAction, TestScriptSetup, TestScriptTestAction, TestScriptTest, TestScriptTeardownAction, TestScriptTeardown, TestScript
from .administrable_product_definition import AdministrableProductDefinitionProperty, AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod, AdministrableProductDefinitionRouteOfAdministrationTargetSpecies, AdministrableProductDefinitionRouteOfAdministration, AdministrableProductDefinition
from .enrollment_response import EnrollmentResponse
from .condition import ConditionStage, ConditionEvidence, Condition
from .specimen import SpecimenCollection, SpecimenProcessing, SpecimenContainer, Specimen
from .message_definition import MessageDefinitionFocus, MessageDefinitionAllowedResponse, MessageDefinition
from .citation import CitationSummary, CitationClassification, CitationStatusDate, CitationRelatesTo, CitationCitedArtifactVersion, CitationCitedArtifactStatusDate, CitationCitedArtifactTitle, CitationCitedArtifactAbstract, CitationCitedArtifactPart, CitationCitedArtifactRelatesTo, CitationCitedArtifactPublicationFormPublishedIn, CitationCitedArtifactPublicationFormPeriodicReleaseDateOfPublication, CitationCitedArtifactPublicationFormPeriodicRelease, CitationCitedArtifactPublicationForm, CitationCitedArtifactWebLocation, CitationCitedArtifactClassificationWhoClassified, CitationCitedArtifactClassification, CitationCitedArtifactContributorshipEntryAffiliationInfo, CitationCitedArtifactContributorshipEntryContributionInstance, CitationCitedArtifactContributorshipEntry, CitationCitedArtifactContributorshipSummary, CitationCitedArtifactContributorship, CitationCitedArtifact, Citation
from .regulated_authorization import RegulatedAuthorizationCase, RegulatedAuthorization
from .structure_definition import StructureDefinitionMapping, StructureDefinitionContext, StructureDefinitionSnapshot, StructureDefinitionDifferential, StructureDefinition
from .verification_result import VerificationResultPrimarySource, VerificationResultAttestation, VerificationResultValidator, VerificationResult
from .evidence import EvidenceVariableDefinition, EvidenceStatisticSampleSize, EvidenceStatisticAttributeEstimate, EvidenceStatisticModelCharacteristicVariable, EvidenceStatisticModelCharacteristic, EvidenceStatistic, EvidenceCertainty, Evidence
from .device_definition import DeviceDefinitionUdiDeviceIdentifier, DeviceDefinitionDeviceName, DeviceDefinitionSpecialization, DeviceDefinitionCapability, DeviceDefinitionProperty, DeviceDefinitionMaterial, DeviceDefinition
from .device import DeviceUdiCarrier, DeviceDeviceName, DeviceSpecialization, DeviceVersion, DeviceProperty, Device
from .catalog_entry import CatalogEntryRelatedEntry, CatalogEntry
from .specimen_definition import SpecimenDefinitionTypeTestedContainerAdditive, SpecimenDefinitionTypeTestedContainer, SpecimenDefinitionTypeTestedHandling, SpecimenDefinitionTypeTested, SpecimenDefinition
from .adverse_event import AdverseEventSuspectEntityCausality, AdverseEventSuspectEntity, AdverseEvent
from .appointment_response import AppointmentResponse
from .nutrition_product import NutritionProductNutrient, NutritionProductIngredient, NutritionProductProductCharacteristic, NutritionProductInstance, NutritionProduct
from .practitioner import PractitionerQualification, Practitioner
from .substance_definition import SubstanceDefinitionMoiety, SubstanceDefinitionProperty, SubstanceDefinitionMolecularWeight, SubstanceDefinitionStructureRepresentation, SubstanceDefinitionStructure, SubstanceDefinitionCode, SubstanceDefinitionNameOfficial, SubstanceDefinitionName, SubstanceDefinitionRelationship, SubstanceDefinitionSourceMaterial, SubstanceDefinition
from .clinical_impression import ClinicalImpressionInvestigation, ClinicalImpressionFinding, ClinicalImpression
from .patient import PatientContact, PatientCommunication, PatientLink, Patient
from .document_manifest import DocumentManifestRelated, DocumentManifest
from .immunization import ImmunizationPerformer, ImmunizationEducation, ImmunizationReaction, ImmunizationProtocolApplied, Immunization
from .subscription_topic import SubscriptionTopicResourceTriggerQueryCriteria, SubscriptionTopicResourceTrigger, SubscriptionTopicEventTrigger, SubscriptionTopicCanFilterBy, SubscriptionTopicNotificationShape, SubscriptionTopic
from .medication_knowledge import MedicationKnowledgeRelatedMedicationKnowledge, MedicationKnowledgeMonograph, MedicationKnowledgeIngredient, MedicationKnowledgeCost, MedicationKnowledgeMonitoringProgram, MedicationKnowledgeAdministrationGuidelinesDosage, MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics, MedicationKnowledgeAdministrationGuidelines, MedicationKnowledgeMedicineClassification, MedicationKnowledgePackaging, MedicationKnowledgeDrugCharacteristic, MedicationKnowledgeRegulatorySubstitution, MedicationKnowledgeRegulatorySchedule, MedicationKnowledgeRegulatoryMaxDispense, MedicationKnowledgeRegulatory, MedicationKnowledgeKinetics, MedicationKnowledge
from .episode_of_care import EpisodeOfCareStatusHistory, EpisodeOfCareDiagnosis, EpisodeOfCare
from .composition import CompositionAttester, CompositionRelatesTo, CompositionEvent, CompositionSection, Composition
from .naming_system import NamingSystemUniqueId, NamingSystem
from .research_element_definition import ResearchElementDefinitionCharacteristic, ResearchElementDefinition
from .contract import ContractContentDefinition, ContractTermSecurityLabel, ContractTermOfferParty, ContractTermOfferAnswer, ContractTermOffer, ContractTermAssetContext, ContractTermAssetValuedItem, ContractTermAsset, ContractTermActionSubject, ContractTermAction, ContractTerm, ContractSigner, ContractFriendly, ContractLegal, ContractRule, Contract
from .consent import ConsentPolicy, ConsentVerification, ConsentProvisionActor, ConsentProvisionData, ConsentProvision, Consent
from .subscription_status import SubscriptionStatusNotificationEvent, SubscriptionStatus
from .device_use_statement import DeviceUseStatement
from .example_scenario import ExampleScenarioActor, ExampleScenarioInstanceVersion, ExampleScenarioInstanceContainedInstance, ExampleScenarioInstance, ExampleScenarioProcessStepOperation, ExampleScenarioProcessStepAlternative, ExampleScenarioProcessStep, ExampleScenarioProcess, ExampleScenario
from .evidence_variable import EvidenceVariableCharacteristicTimeFromStart, EvidenceVariableCharacteristic, EvidenceVariableCategory, EvidenceVariable
from .test_report import TestReportParticipant, TestReportSetupActionOperation, TestReportSetupActionAssert, TestReportSetupAction, TestReportSetup, TestReportTestAction, TestReportTest, TestReportTeardownAction, TestReportTeardown, TestReport
from .claim import ClaimRelated, ClaimPayee, ClaimCareTeam, ClaimSupportingInfo, ClaimDiagnosis, ClaimProcedure, ClaimInsurance, ClaimAccident, ClaimItemDetailSubDetail, ClaimItemDetail, ClaimItem, Claim
from .questionnaire import QuestionnaireItemEnableWhen, QuestionnaireItemAnswerOption, QuestionnaireItemInitial, QuestionnaireItem, Questionnaire
from .vision_prescription import VisionPrescriptionLensSpecificationPrism, VisionPrescriptionLensSpecification, VisionPrescription
from .risk_assessment import RiskAssessmentPrediction, RiskAssessment
from .charge_item_definition import ChargeItemDefinitionApplicability, ChargeItemDefinitionPropertyGroupPriceComponent, ChargeItemDefinitionPropertyGroup, ChargeItemDefinition
from .payment_reconciliation import PaymentReconciliationDetail, PaymentReconciliationProcessNote, PaymentReconciliation
from .guidance_response import GuidanceResponse
from .task import TaskRestriction, TaskInput, TaskOutput, Task
from .ingredient import IngredientManufacturer, IngredientSubstanceStrengthReferenceStrength, IngredientSubstanceStrength, IngredientSubstance, Ingredient
from .coverage_eligibility_request import CoverageEligibilityRequestSupportingInfo, CoverageEligibilityRequestInsurance, CoverageEligibilityRequestItemDiagnosis, CoverageEligibilityRequestItem, CoverageEligibilityRequest
from .enrollment_request import EnrollmentRequest
from .structure_map import StructureMapStructure, StructureMapGroupInput, StructureMapGroupRuleSource, StructureMapGroupRuleTargetParameter, StructureMapGroupRuleTarget, StructureMapGroupRuleDependent, StructureMapGroupRule, StructureMapGroup, StructureMap
from .medicinal_product_definition import MedicinalProductDefinitionContact, MedicinalProductDefinitionNameNamePart, MedicinalProductDefinitionNameCountryLanguage, MedicinalProductDefinitionName, MedicinalProductDefinitionCrossReference, MedicinalProductDefinitionOperation, MedicinalProductDefinitionCharacteristic, MedicinalProductDefinition
from .immunization_evaluation import ImmunizationEvaluation
from .imaging_study import ImagingStudySeriesPerformer, ImagingStudySeriesInstance, ImagingStudySeries, ImagingStudy
from .media import Media
from .message_header import MessageHeaderDestination, MessageHeaderSource, MessageHeaderResponse, MessageHeader
from .explanation_of_benefit import ExplanationOfBenefitRelated, ExplanationOfBenefitPayee, ExplanationOfBenefitCareTeam, ExplanationOfBenefitSupportingInfo, ExplanationOfBenefitDiagnosis, ExplanationOfBenefitProcedure, ExplanationOfBenefitInsurance, ExplanationOfBenefitAccident, ExplanationOfBenefitItemAdjudication, ExplanationOfBenefitItemDetailSubDetail, ExplanationOfBenefitItemDetail, ExplanationOfBenefitItem, ExplanationOfBenefitAddItemDetailSubDetail, ExplanationOfBenefitAddItemDetail, ExplanationOfBenefitAddItem, ExplanationOfBenefitTotal, ExplanationOfBenefitPayment, ExplanationOfBenefitProcessNote, ExplanationOfBenefitBenefitBalanceFinancial, ExplanationOfBenefitBenefitBalance, ExplanationOfBenefit
from .supply_request import SupplyRequestParameter, SupplyRequest
from .immunization_recommendation import ImmunizationRecommendationRecommendationDateCriterion, ImmunizationRecommendationRecommendation, ImmunizationRecommendation
from .coverage_eligibility_response import CoverageEligibilityResponseInsuranceItemBenefit, CoverageEligibilityResponseInsuranceItem, CoverageEligibilityResponseInsurance, CoverageEligibilityResponseError, CoverageEligibilityResponse
from .related_person import RelatedPersonCommunication, RelatedPerson
from .communication_request import CommunicationRequestPayload, CommunicationRequest
from .molecular_sequence import MolecularSequenceReferenceSeq, MolecularSequenceVariant, MolecularSequenceQualityRoc, MolecularSequenceQuality, MolecularSequenceRepository, MolecularSequenceStructureVariantOuter, MolecularSequenceStructureVariantInner, MolecularSequenceStructureVariant, MolecularSequence
from .insurance_plan import InsurancePlanContact, InsurancePlanCoverageBenefitLimit, InsurancePlanCoverageBenefit, InsurancePlanCoverage, InsurancePlanPlanGeneralCost, InsurancePlanPlanSpecificCostBenefitCost, InsurancePlanPlanSpecificCostBenefit, InsurancePlanPlanSpecificCost, InsurancePlanPlan, InsurancePlan
from .medication import MedicationIngredient, MedicationBatch, Medication
from .care_team import CareTeamParticipant, CareTeam
from .operation_definition import OperationDefinitionParameterBinding, OperationDefinitionParameterReferencedFrom, OperationDefinitionParameter, OperationDefinitionOverload, OperationDefinition
from .person import PersonLink, Person
from .diagnostic_report import DiagnosticReportMedia, DiagnosticReport
from .compartment_definition import CompartmentDefinitionResource, CompartmentDefinition
from .service_request import ServiceRequest
from .medication_administration import MedicationAdministrationPerformer, MedicationAdministrationDosage, MedicationAdministration
from .code_system import CodeSystemFilter, CodeSystemProperty, CodeSystemConceptDesignation, CodeSystemConceptProperty, CodeSystemConcept, CodeSystem
from .detected_issue import DetectedIssueEvidence, DetectedIssueMitigation, DetectedIssue
from .questionnaire_response import QuestionnaireResponseItemAnswer, QuestionnaireResponseItem, QuestionnaireResponse
from .endpoint import Endpoint
from .measure import MeasureGroupPopulation, MeasureGroupStratifierComponent, MeasureGroupStratifier, MeasureGroup, MeasureSupplementalData, Measure
from .resource import Resource
from .supply_delivery import SupplyDeliverySuppliedItem, SupplyDelivery
from .research_subject import ResearchSubject
from .organization_affiliation import OrganizationAffiliation
from .medication_statement import MedicationStatement
from .document_reference import DocumentReferenceRelatesTo, DocumentReferenceContent, DocumentReferenceContext, DocumentReference
from .schedule import Schedule
from .account import AccountCoverage, AccountGuarantor, Account
from .allergy_intolerance import AllergyIntoleranceReaction, AllergyIntolerance
from .encounter import EncounterStatusHistory, EncounterClassHistory, EncounterParticipant, EncounterDiagnosis, EncounterHospitalization, EncounterLocation, Encounter
from .research_study import ResearchStudyArm, ResearchStudyObjective, ResearchStudy
from .biologically_derived_product import BiologicallyDerivedProductCollection, BiologicallyDerivedProductProcessing, BiologicallyDerivedProductManipulation, BiologicallyDerivedProductStorage, BiologicallyDerivedProduct
from .medication_dispense import MedicationDispensePerformer, MedicationDispenseSubstitution, MedicationDispense
from .request_group import RequestGroupActionCondition, RequestGroupActionRelatedAction, RequestGroupAction, RequestGroup
from .nutrition_order import NutritionOrderOralDietNutrient, NutritionOrderOralDietTexture, NutritionOrderOralDiet, NutritionOrderSupplement, NutritionOrderEnteralFormulaAdministration, NutritionOrderEnteralFormula, NutritionOrder
from .operation_outcome import OperationOutcomeIssue, OperationOutcome
from .observation import ObservationReferenceRange, ObservationComponent, Observation
from .slot import Slot
from .implementation_guide import ImplementationGuideDependsOn, ImplementationGuideGlobal, ImplementationGuideDefinitionGrouping, ImplementationGuideDefinitionResource, ImplementationGuideDefinitionPage, ImplementationGuideDefinitionParameter, ImplementationGuideDefinitionTemplate, ImplementationGuideDefinition, ImplementationGuideManifestResource, ImplementationGuideManifestPage, ImplementationGuideManifest, ImplementationGuide
from .device_request import DeviceRequestParameter, DeviceRequest
from .measure_report import MeasureReportGroupPopulation, MeasureReportGroupStratifierStratumComponent, MeasureReportGroupStratifierStratumPopulation, MeasureReportGroupStratifierStratum, MeasureReportGroupStratifier, MeasureReportGroup, MeasureReport
from .linkage import LinkageItem, Linkage
from .binary import Binary
from .domain_resource import DomainResource
from .plan_definition import PlanDefinitionGoalTarget, PlanDefinitionGoal, PlanDefinitionActionCondition, PlanDefinitionActionRelatedAction, PlanDefinitionActionParticipant, PlanDefinitionActionDynamicValue, PlanDefinitionAction, PlanDefinition
from .invoice import InvoiceParticipant, InvoiceLineItemPriceComponent, InvoiceLineItem, Invoice
from .goal import GoalTarget, Goal
from .coverage import CoverageClass, CoverageCostToBeneficiaryException, CoverageCostToBeneficiary, Coverage
from .audit_event import AuditEventAgentNetwork, AuditEventAgent, AuditEventSource, AuditEventEntityDetail, AuditEventEntity, AuditEvent
from .bundle import BundleLink, BundleEntrySearch, BundleEntryRequest, BundleEntryResponse, BundleEntry, Bundle
from .payment_notice import PaymentNotice
from .location import LocationPosition, LocationHoursOfOperation, Location
from .care_plan import CarePlanActivityDetail, CarePlanActivity, CarePlan
from .parameters import ParametersParameter, Parameters
from .appointment import AppointmentParticipant, Appointment
from .organization import OrganizationContact, Organization
from .basic import Basic
from .charge_item import ChargeItemPerformer, ChargeItem
from .procedure import ProcedurePerformer, ProcedureFocalDevice, Procedure
from .packaged_product_definition import PackagedProductDefinitionLegalStatusOfSupply, PackagedProductDefinitionPackageShelfLifeStorage, PackagedProductDefinitionPackageProperty, PackagedProductDefinitionPackageContainedItem, PackagedProductDefinitionPackage, PackagedProductDefinition
from .substance import SubstanceInstance, SubstanceIngredient, Substance
from .library import Library
from .device_metric import DeviceMetricCalibration, DeviceMetric

__all__ = [
    "GroupCharacteristic",
    "GroupMember",
    "Group",
    "ActivityDefinitionParticipant",
    "ActivityDefinitionDynamicValue",
    "ActivityDefinition",
    "Flag",
    "EventDefinition",
    "HealthcareServiceEligibility",
    "HealthcareServiceAvailableTime",
    "HealthcareServiceNotAvailable",
    "HealthcareService",
    "SubscriptionChannel",
    "Subscription",
    "SearchParameterComponent",
    "SearchParameter",
    "ClinicalUseDefinitionContraindicationOtherTherapy",
    "ClinicalUseDefinitionContraindication",
    "ClinicalUseDefinitionIndication",
    "ClinicalUseDefinitionInteractionInteractant",
    "ClinicalUseDefinitionInteraction",
    "ClinicalUseDefinitionUndesirableEffect",
    "ClinicalUseDefinitionWarning",
    "ClinicalUseDefinition",
    "BodyStructure",
    "GraphDefinitionLinkTargetCompartment",
    "GraphDefinitionLinkTarget",
    "GraphDefinitionLink",
    "GraphDefinition",
    "TerminologyCapabilitiesSoftware",
    "TerminologyCapabilitiesImplementation",
    "TerminologyCapabilitiesCodeSystemVersionFilter",
    "TerminologyCapabilitiesCodeSystemVersion",
    "TerminologyCapabilitiesCodeSystem",
    "TerminologyCapabilitiesExpansionParameter",
    "TerminologyCapabilitiesExpansion",
    "TerminologyCapabilitiesValidateCode",
    "TerminologyCapabilitiesTranslation",
    "TerminologyCapabilitiesClosure",
    "TerminologyCapabilities",
    "PractitionerRoleAvailableTime",
    "PractitionerRoleNotAvailable",
    "PractitionerRole",
    "CapabilityStatementSoftware",
    "CapabilityStatementImplementation",
    "CapabilityStatementRestSecurity",
    "CapabilityStatementRestResourceInteraction",
    "CapabilityStatementRestResourceSearchParam",
    "CapabilityStatementRestResourceOperation",
    "CapabilityStatementRestResource",
    "CapabilityStatementRestInteraction",
    "CapabilityStatementRest",
    "CapabilityStatementMessagingEndpoint",
    "CapabilityStatementMessagingSupportedMessage",
    "CapabilityStatementMessaging",
    "CapabilityStatementDocument",
    "CapabilityStatement",
    "ConceptMapGroupElementTargetDependsOn",
    "ConceptMapGroupElementTarget",
    "ConceptMapGroupElement",
    "ConceptMapGroupUnmapped",
    "ConceptMapGroup",
    "ConceptMap",
    "ListEntry",
    "List",
    "CommunicationPayload",
    "Communication",
    "ResearchDefinition",
    "ValueSetComposeIncludeConceptDesignation",
    "ValueSetComposeIncludeConcept",
    "ValueSetComposeIncludeFilter",
    "ValueSetComposeInclude",
    "ValueSetCompose",
    "ValueSetExpansionParameter",
    "ValueSetExpansionContains",
    "ValueSetExpansion",
    "ValueSet",
    "ProvenanceAgent",
    "ProvenanceEntity",
    "Provenance",
    "ClaimResponseItemAdjudication",
    "ClaimResponseItemDetailSubDetail",
    "ClaimResponseItemDetail",
    "ClaimResponseItem",
    "ClaimResponseAddItemDetailSubDetail",
    "ClaimResponseAddItemDetail",
    "ClaimResponseAddItem",
    "ClaimResponseTotal",
    "ClaimResponsePayment",
    "ClaimResponseProcessNote",
    "ClaimResponseInsurance",
    "ClaimResponseError",
    "ClaimResponse",
    "ObservationDefinitionQuantitativeDetails",
    "ObservationDefinitionQualifiedInterval",
    "ObservationDefinition",
    "FamilyMemberHistoryCondition",
    "FamilyMemberHistory",
    "EvidenceReportSubjectCharacteristic",
    "EvidenceReportSubject",
    "EvidenceReportRelatesTo",
    "EvidenceReportSection",
    "EvidenceReport",
    "MedicationRequestDispenseRequestInitialFill",
    "MedicationRequestDispenseRequest",
    "MedicationRequestSubstitution",
    "MedicationRequest",
    "ManufacturedItemDefinitionProperty",
    "ManufacturedItemDefinition",
    "TestScriptOrigin",
    "TestScriptDestination",
    "TestScriptMetadataLink",
    "TestScriptMetadataCapability",
    "TestScriptMetadata",
    "TestScriptFixture",
    "TestScriptVariable",
    "TestScriptSetupActionOperationRequestHeader",
    "TestScriptSetupActionOperation",
    "TestScriptSetupActionAssert",
    "TestScriptSetupAction",
    "TestScriptSetup",
    "TestScriptTestAction",
    "TestScriptTest",
    "TestScriptTeardownAction",
    "TestScriptTeardown",
    "TestScript",
    "AdministrableProductDefinitionProperty",
    "AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod",
    "AdministrableProductDefinitionRouteOfAdministrationTargetSpecies",
    "AdministrableProductDefinitionRouteOfAdministration",
    "AdministrableProductDefinition",
    "EnrollmentResponse",
    "ConditionStage",
    "ConditionEvidence",
    "Condition",
    "SpecimenCollection",
    "SpecimenProcessing",
    "SpecimenContainer",
    "Specimen",
    "MessageDefinitionFocus",
    "MessageDefinitionAllowedResponse",
    "MessageDefinition",
    "CitationSummary",
    "CitationClassification",
    "CitationStatusDate",
    "CitationRelatesTo",
    "CitationCitedArtifactVersion",
    "CitationCitedArtifactStatusDate",
    "CitationCitedArtifactTitle",
    "CitationCitedArtifactAbstract",
    "CitationCitedArtifactPart",
    "CitationCitedArtifactRelatesTo",
    "CitationCitedArtifactPublicationFormPublishedIn",
    "CitationCitedArtifactPublicationFormPeriodicReleaseDateOfPublication",
    "CitationCitedArtifactPublicationFormPeriodicRelease",
    "CitationCitedArtifactPublicationForm",
    "CitationCitedArtifactWebLocation",
    "CitationCitedArtifactClassificationWhoClassified",
    "CitationCitedArtifactClassification",
    "CitationCitedArtifactContributorshipEntryAffiliationInfo",
    "CitationCitedArtifactContributorshipEntryContributionInstance",
    "CitationCitedArtifactContributorshipEntry",
    "CitationCitedArtifactContributorshipSummary",
    "CitationCitedArtifactContributorship",
    "CitationCitedArtifact",
    "Citation",
    "RegulatedAuthorizationCase",
    "RegulatedAuthorization",
    "StructureDefinitionMapping",
    "StructureDefinitionContext",
    "StructureDefinitionSnapshot",
    "StructureDefinitionDifferential",
    "StructureDefinition",
    "VerificationResultPrimarySource",
    "VerificationResultAttestation",
    "VerificationResultValidator",
    "VerificationResult",
    "EvidenceVariableDefinition",
    "EvidenceStatisticSampleSize",
    "EvidenceStatisticAttributeEstimate",
    "EvidenceStatisticModelCharacteristicVariable",
    "EvidenceStatisticModelCharacteristic",
    "EvidenceStatistic",
    "EvidenceCertainty",
    "Evidence",
    "DeviceDefinitionUdiDeviceIdentifier",
    "DeviceDefinitionDeviceName",
    "DeviceDefinitionSpecialization",
    "DeviceDefinitionCapability",
    "DeviceDefinitionProperty",
    "DeviceDefinitionMaterial",
    "DeviceDefinition",
    "DeviceUdiCarrier",
    "DeviceDeviceName",
    "DeviceSpecialization",
    "DeviceVersion",
    "DeviceProperty",
    "Device",
    "CatalogEntryRelatedEntry",
    "CatalogEntry",
    "SpecimenDefinitionTypeTestedContainerAdditive",
    "SpecimenDefinitionTypeTestedContainer",
    "SpecimenDefinitionTypeTestedHandling",
    "SpecimenDefinitionTypeTested",
    "SpecimenDefinition",
    "AdverseEventSuspectEntityCausality",
    "AdverseEventSuspectEntity",
    "AdverseEvent",
    "AppointmentResponse",
    "NutritionProductNutrient",
    "NutritionProductIngredient",
    "NutritionProductProductCharacteristic",
    "NutritionProductInstance",
    "NutritionProduct",
    "PractitionerQualification",
    "Practitioner",
    "SubstanceDefinitionMoiety",
    "SubstanceDefinitionProperty",
    "SubstanceDefinitionMolecularWeight",
    "SubstanceDefinitionStructureRepresentation",
    "SubstanceDefinitionStructure",
    "SubstanceDefinitionCode",
    "SubstanceDefinitionNameOfficial",
    "SubstanceDefinitionName",
    "SubstanceDefinitionRelationship",
    "SubstanceDefinitionSourceMaterial",
    "SubstanceDefinition",
    "ClinicalImpressionInvestigation",
    "ClinicalImpressionFinding",
    "ClinicalImpression",
    "PatientContact",
    "PatientCommunication",
    "PatientLink",
    "Patient",
    "DocumentManifestRelated",
    "DocumentManifest",
    "ImmunizationPerformer",
    "ImmunizationEducation",
    "ImmunizationReaction",
    "ImmunizationProtocolApplied",
    "Immunization",
    "SubscriptionTopicResourceTriggerQueryCriteria",
    "SubscriptionTopicResourceTrigger",
    "SubscriptionTopicEventTrigger",
    "SubscriptionTopicCanFilterBy",
    "SubscriptionTopicNotificationShape",
    "SubscriptionTopic",
    "MedicationKnowledgeRelatedMedicationKnowledge",
    "MedicationKnowledgeMonograph",
    "MedicationKnowledgeIngredient",
    "MedicationKnowledgeCost",
    "MedicationKnowledgeMonitoringProgram",
    "MedicationKnowledgeAdministrationGuidelinesDosage",
    "MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics",
    "MedicationKnowledgeAdministrationGuidelines",
    "MedicationKnowledgeMedicineClassification",
    "MedicationKnowledgePackaging",
    "MedicationKnowledgeDrugCharacteristic",
    "MedicationKnowledgeRegulatorySubstitution",
    "MedicationKnowledgeRegulatorySchedule",
    "MedicationKnowledgeRegulatoryMaxDispense",
    "MedicationKnowledgeRegulatory",
    "MedicationKnowledgeKinetics",
    "MedicationKnowledge",
    "EpisodeOfCareStatusHistory",
    "EpisodeOfCareDiagnosis",
    "EpisodeOfCare",
    "CompositionAttester",
    "CompositionRelatesTo",
    "CompositionEvent",
    "CompositionSection",
    "Composition",
    "NamingSystemUniqueId",
    "NamingSystem",
    "ResearchElementDefinitionCharacteristic",
    "ResearchElementDefinition",
    "ContractContentDefinition",
    "ContractTermSecurityLabel",
    "ContractTermOfferParty",
    "ContractTermOfferAnswer",
    "ContractTermOffer",
    "ContractTermAssetContext",
    "ContractTermAssetValuedItem",
    "ContractTermAsset",
    "ContractTermActionSubject",
    "ContractTermAction",
    "ContractTerm",
    "ContractSigner",
    "ContractFriendly",
    "ContractLegal",
    "ContractRule",
    "Contract",
    "ConsentPolicy",
    "ConsentVerification",
    "ConsentProvisionActor",
    "ConsentProvisionData",
    "ConsentProvision",
    "Consent",
    "SubscriptionStatusNotificationEvent",
    "SubscriptionStatus",
    "DeviceUseStatement",
    "ExampleScenarioActor",
    "ExampleScenarioInstanceVersion",
    "ExampleScenarioInstanceContainedInstance",
    "ExampleScenarioInstance",
    "ExampleScenarioProcessStepOperation",
    "ExampleScenarioProcessStepAlternative",
    "ExampleScenarioProcessStep",
    "ExampleScenarioProcess",
    "ExampleScenario",
    "EvidenceVariableCharacteristicTimeFromStart",
    "EvidenceVariableCharacteristic",
    "EvidenceVariableCategory",
    "EvidenceVariable",
    "TestReportParticipant",
    "TestReportSetupActionOperation",
    "TestReportSetupActionAssert",
    "TestReportSetupAction",
    "TestReportSetup",
    "TestReportTestAction",
    "TestReportTest",
    "TestReportTeardownAction",
    "TestReportTeardown",
    "TestReport",
    "ClaimRelated",
    "ClaimPayee",
    "ClaimCareTeam",
    "ClaimSupportingInfo",
    "ClaimDiagnosis",
    "ClaimProcedure",
    "ClaimInsurance",
    "ClaimAccident",
    "ClaimItemDetailSubDetail",
    "ClaimItemDetail",
    "ClaimItem",
    "Claim",
    "QuestionnaireItemEnableWhen",
    "QuestionnaireItemAnswerOption",
    "QuestionnaireItemInitial",
    "QuestionnaireItem",
    "Questionnaire",
    "VisionPrescriptionLensSpecificationPrism",
    "VisionPrescriptionLensSpecification",
    "VisionPrescription",
    "RiskAssessmentPrediction",
    "RiskAssessment",
    "ChargeItemDefinitionApplicability",
    "ChargeItemDefinitionPropertyGroupPriceComponent",
    "ChargeItemDefinitionPropertyGroup",
    "ChargeItemDefinition",
    "PaymentReconciliationDetail",
    "PaymentReconciliationProcessNote",
    "PaymentReconciliation",
    "GuidanceResponse",
    "TaskRestriction",
    "TaskInput",
    "TaskOutput",
    "Task",
    "IngredientManufacturer",
    "IngredientSubstanceStrengthReferenceStrength",
    "IngredientSubstanceStrength",
    "IngredientSubstance",
    "Ingredient",
    "CoverageEligibilityRequestSupportingInfo",
    "CoverageEligibilityRequestInsurance",
    "CoverageEligibilityRequestItemDiagnosis",
    "CoverageEligibilityRequestItem",
    "CoverageEligibilityRequest",
    "EnrollmentRequest",
    "StructureMapStructure",
    "StructureMapGroupInput",
    "StructureMapGroupRuleSource",
    "StructureMapGroupRuleTargetParameter",
    "StructureMapGroupRuleTarget",
    "StructureMapGroupRuleDependent",
    "StructureMapGroupRule",
    "StructureMapGroup",
    "StructureMap",
    "MedicinalProductDefinitionContact",
    "MedicinalProductDefinitionNameNamePart",
    "MedicinalProductDefinitionNameCountryLanguage",
    "MedicinalProductDefinitionName",
    "MedicinalProductDefinitionCrossReference",
    "MedicinalProductDefinitionOperation",
    "MedicinalProductDefinitionCharacteristic",
    "MedicinalProductDefinition",
    "ImmunizationEvaluation",
    "ImagingStudySeriesPerformer",
    "ImagingStudySeriesInstance",
    "ImagingStudySeries",
    "ImagingStudy",
    "Media",
    "MessageHeaderDestination",
    "MessageHeaderSource",
    "MessageHeaderResponse",
    "MessageHeader",
    "ExplanationOfBenefitRelated",
    "ExplanationOfBenefitPayee",
    "ExplanationOfBenefitCareTeam",
    "ExplanationOfBenefitSupportingInfo",
    "ExplanationOfBenefitDiagnosis",
    "ExplanationOfBenefitProcedure",
    "ExplanationOfBenefitInsurance",
    "ExplanationOfBenefitAccident",
    "ExplanationOfBenefitItemAdjudication",
    "ExplanationOfBenefitItemDetailSubDetail",
    "ExplanationOfBenefitItemDetail",
    "ExplanationOfBenefitItem",
    "ExplanationOfBenefitAddItemDetailSubDetail",
    "ExplanationOfBenefitAddItemDetail",
    "ExplanationOfBenefitAddItem",
    "ExplanationOfBenefitTotal",
    "ExplanationOfBenefitPayment",
    "ExplanationOfBenefitProcessNote",
    "ExplanationOfBenefitBenefitBalanceFinancial",
    "ExplanationOfBenefitBenefitBalance",
    "ExplanationOfBenefit",
    "SupplyRequestParameter",
    "SupplyRequest",
    "ImmunizationRecommendationRecommendationDateCriterion",
    "ImmunizationRecommendationRecommendation",
    "ImmunizationRecommendation",
    "CoverageEligibilityResponseInsuranceItemBenefit",
    "CoverageEligibilityResponseInsuranceItem",
    "CoverageEligibilityResponseInsurance",
    "CoverageEligibilityResponseError",
    "CoverageEligibilityResponse",
    "RelatedPersonCommunication",
    "RelatedPerson",
    "CommunicationRequestPayload",
    "CommunicationRequest",
    "MolecularSequenceReferenceSeq",
    "MolecularSequenceVariant",
    "MolecularSequenceQualityRoc",
    "MolecularSequenceQuality",
    "MolecularSequenceRepository",
    "MolecularSequenceStructureVariantOuter",
    "MolecularSequenceStructureVariantInner",
    "MolecularSequenceStructureVariant",
    "MolecularSequence",
    "InsurancePlanContact",
    "InsurancePlanCoverageBenefitLimit",
    "InsurancePlanCoverageBenefit",
    "InsurancePlanCoverage",
    "InsurancePlanPlanGeneralCost",
    "InsurancePlanPlanSpecificCostBenefitCost",
    "InsurancePlanPlanSpecificCostBenefit",
    "InsurancePlanPlanSpecificCost",
    "InsurancePlanPlan",
    "InsurancePlan",
    "MedicationIngredient",
    "MedicationBatch",
    "Medication",
    "CareTeamParticipant",
    "CareTeam",
    "OperationDefinitionParameterBinding",
    "OperationDefinitionParameterReferencedFrom",
    "OperationDefinitionParameter",
    "OperationDefinitionOverload",
    "OperationDefinition",
    "PersonLink",
    "Person",
    "DiagnosticReportMedia",
    "DiagnosticReport",
    "CompartmentDefinitionResource",
    "CompartmentDefinition",
    "ServiceRequest",
    "MedicationAdministrationPerformer",
    "MedicationAdministrationDosage",
    "MedicationAdministration",
    "CodeSystemFilter",
    "CodeSystemProperty",
    "CodeSystemConceptDesignation",
    "CodeSystemConceptProperty",
    "CodeSystemConcept",
    "CodeSystem",
    "DetectedIssueEvidence",
    "DetectedIssueMitigation",
    "DetectedIssue",
    "QuestionnaireResponseItemAnswer",
    "QuestionnaireResponseItem",
    "QuestionnaireResponse",
    "Endpoint",
    "MeasureGroupPopulation",
    "MeasureGroupStratifierComponent",
    "MeasureGroupStratifier",
    "MeasureGroup",
    "MeasureSupplementalData",
    "Measure",
    "Resource",
    "SupplyDeliverySuppliedItem",
    "SupplyDelivery",
    "ResearchSubject",
    "OrganizationAffiliation",
    "MedicationStatement",
    "DocumentReferenceRelatesTo",
    "DocumentReferenceContent",
    "DocumentReferenceContext",
    "DocumentReference",
    "Schedule",
    "AccountCoverage",
    "AccountGuarantor",
    "Account",
    "AllergyIntoleranceReaction",
    "AllergyIntolerance",
    "EncounterStatusHistory",
    "EncounterClassHistory",
    "EncounterParticipant",
    "EncounterDiagnosis",
    "EncounterHospitalization",
    "EncounterLocation",
    "Encounter",
    "ResearchStudyArm",
    "ResearchStudyObjective",
    "ResearchStudy",
    "BiologicallyDerivedProductCollection",
    "BiologicallyDerivedProductProcessing",
    "BiologicallyDerivedProductManipulation",
    "BiologicallyDerivedProductStorage",
    "BiologicallyDerivedProduct",
    "MedicationDispensePerformer",
    "MedicationDispenseSubstitution",
    "MedicationDispense",
    "RequestGroupActionCondition",
    "RequestGroupActionRelatedAction",
    "RequestGroupAction",
    "RequestGroup",
    "NutritionOrderOralDietNutrient",
    "NutritionOrderOralDietTexture",
    "NutritionOrderOralDiet",
    "NutritionOrderSupplement",
    "NutritionOrderEnteralFormulaAdministration",
    "NutritionOrderEnteralFormula",
    "NutritionOrder",
    "OperationOutcomeIssue",
    "OperationOutcome",
    "ObservationReferenceRange",
    "ObservationComponent",
    "Observation",
    "Slot",
    "ImplementationGuideDependsOn",
    "ImplementationGuideGlobal",
    "ImplementationGuideDefinitionGrouping",
    "ImplementationGuideDefinitionResource",
    "ImplementationGuideDefinitionPage",
    "ImplementationGuideDefinitionParameter",
    "ImplementationGuideDefinitionTemplate",
    "ImplementationGuideDefinition",
    "ImplementationGuideManifestResource",
    "ImplementationGuideManifestPage",
    "ImplementationGuideManifest",
    "ImplementationGuide",
    "DeviceRequestParameter",
    "DeviceRequest",
    "MeasureReportGroupPopulation",
    "MeasureReportGroupStratifierStratumComponent",
    "MeasureReportGroupStratifierStratumPopulation",
    "MeasureReportGroupStratifierStratum",
    "MeasureReportGroupStratifier",
    "MeasureReportGroup",
    "MeasureReport",
    "LinkageItem",
    "Linkage",
    "Binary",
    "DomainResource",
    "PlanDefinitionGoalTarget",
    "PlanDefinitionGoal",
    "PlanDefinitionActionCondition",
    "PlanDefinitionActionRelatedAction",
    "PlanDefinitionActionParticipant",
    "PlanDefinitionActionDynamicValue",
    "PlanDefinitionAction",
    "PlanDefinition",
    "InvoiceParticipant",
    "InvoiceLineItemPriceComponent",
    "InvoiceLineItem",
    "Invoice",
    "GoalTarget",
    "Goal",
    "CoverageClass",
    "CoverageCostToBeneficiaryException",
    "CoverageCostToBeneficiary",
    "Coverage",
    "AuditEventAgentNetwork",
    "AuditEventAgent",
    "AuditEventSource",
    "AuditEventEntityDetail",
    "AuditEventEntity",
    "AuditEvent",
    "BundleLink",
    "BundleEntrySearch",
    "BundleEntryRequest",
    "BundleEntryResponse",
    "BundleEntry",
    "Bundle",
    "PaymentNotice",
    "LocationPosition",
    "LocationHoursOfOperation",
    "Location",
    "CarePlanActivityDetail",
    "CarePlanActivity",
    "CarePlan",
    "ParametersParameter",
    "Parameters",
    "AppointmentParticipant",
    "Appointment",
    "OrganizationContact",
    "Organization",
    "Basic",
    "ChargeItemPerformer",
    "ChargeItem",
    "ProcedurePerformer",
    "ProcedureFocalDevice",
    "Procedure",
    "PackagedProductDefinitionLegalStatusOfSupply",
    "PackagedProductDefinitionPackageShelfLifeStorage",
    "PackagedProductDefinitionPackageProperty",
    "PackagedProductDefinitionPackageContainedItem",
    "PackagedProductDefinitionPackage",
    "PackagedProductDefinition",
    "SubstanceInstance",
    "SubstanceIngredient",
    "Substance",
    "Library",
    "DeviceMetricCalibration",
    "DeviceMetric",
]
