# Code autogenerated by Fhircraft 0.2.0 on 2025-10-03 08:18:20.971010.

# Fhircraft modules
import fhircraft
from fhircraft.utils import model_rebuild_all
from fhircraft.fhir.resources.datatypes.primitives import *
from fhircraft.fhir.resources.base import FHIRBaseModel
import fhircraft.fhir.resources.validators as fhir_validators
# Pydantic modules
from pydantic import Field, field_validator, model_validator, BaseModel
from pydantic.fields import FieldInfo

# Standard modules
from typing import Optional, Literal, Union
from enum import Enum
NoneType = type(None)

# Dynamic modules 
 
from fhircraft.fhir.resources.base import FHIRBaseModel
 
from typing import Optional,List,Literal
 
from fhircraft.fhir.resources.datatypes.primitives import String,Uri,Code
 
from fhircraft.fhir.resources.datatypes.R4.complex_types import Element,Meta,Narrative,Resource,Extension,BackboneElement,CodeableConcept,Reference,Identifier,Quantity,Range

 
class SubstanceReferenceInformationGene(BackboneElement):
    """
    Todo.
    """
    geneSequenceOrigin: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    gene: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    source: Optional[List[Reference]] = Field(
        description="Todo",
        default=None,
    )
    @field_validator(*('source', 'gene', 'geneSequenceOrigin', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension'), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):    
        return fhir_validators.validate_element_constraint(cls, value, 
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )



 
class SubstanceReferenceInformationGeneElement(BackboneElement):
    """
    Todo.
    """
    type: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    element: Optional[Identifier] = Field(
        description="Todo",
        default=None,
    )
    source: Optional[List[Reference]] = Field(
        description="Todo",
        default=None,
    )
    @field_validator(*('source', 'element', 'type', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension'), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):    
        return fhir_validators.validate_element_constraint(cls, value, 
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )



 
class SubstanceReferenceInformationClassification(BackboneElement):
    """
    Todo.
    """
    domain: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    classification: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    subtype: Optional[List[CodeableConcept]] = Field(
        description="Todo",
        default=None,
    )
    source: Optional[List[Reference]] = Field(
        description="Todo",
        default=None,
    )
    @field_validator(*('source', 'subtype', 'classification', 'domain', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension'), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):    
        return fhir_validators.validate_element_constraint(cls, value, 
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )



 
class SubstanceReferenceInformationTarget(BackboneElement):
    """
    Todo.
    """
    target: Optional[Identifier] = Field(
        description="Todo",
        default=None,
    )
    type: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    interaction: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    organism: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    organismType: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    amountQuantity: Optional[Quantity] = Field(
        description="Todo",
        default=None,
    )
    amountRange: Optional[Range] = Field(
        description="Todo",
        default=None,
    )
    amountString: Optional[String] = Field(
        description="Todo",
        default=None,
    )
    amountType: Optional[CodeableConcept] = Field(
        description="Todo",
        default=None,
    )
    source: Optional[List[Reference]] = Field(
        description="Todo",
        default=None,
    )
    @property 
    def amount(self):
        return fhir_validators.get_type_choice_value_by_base(self, 
            base="amount",
        )
    @field_validator(*('source', 'amountType', 'organismType', 'organism', 'interaction', 'type', 'target', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension', 'modifierExtension', 'extension'), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):    
        return fhir_validators.validate_element_constraint(cls, value, 
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )



    @model_validator(mode="after")
    def amount_type_choice_validator(self):
        return fhir_validators.validate_type_choice_element( 
            self,
            field_types=[Quantity, Range, String],
            field_name_base="amount",
            required=False,
        )

 
class SubstanceReferenceInformation(FHIRBaseModel):
    """
    Todo.
    """
    id: Optional[String] = Field(
        description="Logical id of this artifact",
        default=None,
    )
    id_ext: Optional[Element] = Field(
        description="Placeholder element for id extensions",
        default=None,
        alias="_id",
    )
    meta: Optional[Meta] = Field(
        description="Metadata about the resource.",
        default_factory=lambda: Meta(versionId='4.0.1', profile=['http://hl7.org/fhir/StructureDefinition/SubstanceReferenceInformation']),
    )
    implicitRules: Optional[Uri] = Field(
        description="A set of rules under which this content was created",
        default=None,
    )
    implicitRules_ext: Optional[Element] = Field(
        description="Placeholder element for implicitRules extensions",
        default=None,
        alias="_implicitRules",
    )
    language: Optional[Code] = Field(
        description="Language of the resource content",
        default=None,
    )
    language_ext: Optional[Element] = Field(
        description="Placeholder element for language extensions",
        default=None,
        alias="_language",
    )
    text: Optional[Narrative] = Field(
        description="Text summary of the resource, for human interpretation",
        default=None,
    )
    contained: Optional[List[Resource]] = Field(
        description="Contained, inline Resources",
        default=None,
    )
    extension: Optional[List[Extension]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    modifierExtension: Optional[List[Extension]] = Field(
        description="Extensions that cannot be ignored",
        default=None,
    )
    comment: Optional[String] = Field(
        description="Todo",
        default=None,
    )
    comment_ext: Optional[Element] = Field(
        description="Placeholder element for comment extensions",
        default=None,
        alias="_comment",
    )
    gene: Optional[List[SubstanceReferenceInformationGene]] = Field(
        description="Todo",
        default=None,
    )
    geneElement: Optional[List[SubstanceReferenceInformationGeneElement]] = Field(
        description="Todo",
        default=None,
    )
    classification: Optional[List[SubstanceReferenceInformationClassification]] = Field(
        description="Todo",
        default=None,
    )
    target: Optional[List[SubstanceReferenceInformationTarget]] = Field(
        description="Todo",
        default=None,
    )
    resourceType: Literal['SubstanceReferenceInformation'] = Field(
        description=None,
        default="SubstanceReferenceInformation",
    )
    @field_validator(*('target', 'classification', 'geneElement', 'gene', 'comment', 'modifierExtension', 'extension', 'text', 'language', 'implicitRules', 'meta'), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):    
        return fhir_validators.validate_element_constraint(cls, value, 
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*('modifierExtension', 'extension'), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):    
        return fhir_validators.validate_element_constraint(cls, value, 
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @field_validator(*('contained',), mode="plain", check_fields=None)
    @classmethod
    def contained_FHIR_resource_validator(cls, value):    
        return fhir_validators.validate_contained_resource(cls, value, 
            release="R4",
        )

    @model_validator(mode="after")
    def FHIR_dom_2_constraint_model_validator(self):
        return fhir_validators.validate_model_constraint( 
            self,
            expression="contained.contained.empty()",
            human="If the resource is contained in another resource, it SHALL NOT contain nested Resources",
            key="dom-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_3_constraint_model_validator(self):
        return fhir_validators.validate_model_constraint( 
            self,
            expression="contained.where((('#'+id in (%resource.descendants().reference | %resource.descendants().as(canonical) | %resource.descendants().as(uri) | %resource.descendants().as(url))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(canonical) = '#').exists()).not()).trace('unmatched', id).empty()",
            human="If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
            key="dom-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_4_constraint_model_validator(self):
        return fhir_validators.validate_model_constraint( 
            self,
            expression="contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
            human="If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
            key="dom-4",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_5_constraint_model_validator(self):
        return fhir_validators.validate_model_constraint( 
            self,
            expression="contained.meta.security.empty()",
            human="If a resource is contained in another resource, it SHALL NOT have a security label",
            key="dom-5",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_6_constraint_model_validator(self):
        return fhir_validators.validate_model_constraint( 
            self,
            expression="text.`div`.exists()",
            human="A resource should have narrative for robust management",
            key="dom-6",
            severity="warning",
        )


